// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/messaging/ws.proto

package messaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientEnvelope_Auth
	//	*ClientEnvelope_Subscribe
	//	*ClientEnvelope_Unsubscribe
	//	*ClientEnvelope_Typing
	Payload       isClientEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEnvelope) Reset() {
	*x = ClientEnvelope{}
	mi := &file_proto_messaging_ws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEnvelope) ProtoMessage() {}

func (x *ClientEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_ws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEnvelope.ProtoReflect.Descriptor instead.
func (*ClientEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_messaging_ws_proto_rawDescGZIP(), []int{0}
}

func (x *ClientEnvelope) GetPayload() isClientEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientEnvelope) GetAuth() *AuthRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *ClientEnvelope) GetSubscribe() *SubscribeRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *ClientEnvelope) GetUnsubscribe() *UnsubscribeRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *ClientEnvelope) GetTyping() *TypingRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_Typing); ok {
			return x.Typing
		}
	}
	return nil
}

type isClientEnvelope_Payload interface {
	isClientEnvelope_Payload()
}

type ClientEnvelope_Auth struct {
	Auth *AuthRequest `protobuf:"bytes,1,opt,name=auth,proto3,oneof"`
}

type ClientEnvelope_Subscribe struct {
	Subscribe *SubscribeRequest `protobuf:"bytes,2,opt,name=subscribe,proto3,oneof"`
}

type ClientEnvelope_Unsubscribe struct {
	Unsubscribe *UnsubscribeRequest `protobuf:"bytes,3,opt,name=unsubscribe,proto3,oneof"`
}

type ClientEnvelope_Typing struct {
	Typing *TypingRequest `protobuf:"bytes,4,opt,name=typing,proto3,oneof"`
}

func (*ClientEnvelope_Auth) isClientEnvelope_Payload() {}

func (*ClientEnvelope_Subscribe) isClientEnvelope_Payload() {}

func (*ClientEnvelope_Unsubscribe) isClientEnvelope_Payload() {}

func (*ClientEnvelope_Typing) isClientEnvelope_Payload() {}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_proto_messaging_ws_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_ws_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_ws_proto_rawDescGZIP(), []int{1}
}

func (x *AuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_messaging_ws_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_ws_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_ws_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_proto_messaging_ws_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_ws_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_ws_proto_rawDescGZIP(), []int{3}
}

func (x *UnsubscribeRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type TypingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypingRequest) Reset() {
	*x = TypingRequest{}
	mi := &file_proto_messaging_ws_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingRequest) ProtoMessage() {}

func (x *TypingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_ws_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingRequest.ProtoReflect.Descriptor instead.
func (*TypingRequest) Descriptor() ([]byte, []int) {
	return file_proto_messaging_ws_proto_rawDescGZIP(), []int{4}
}

func (x *TypingRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type ServerEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerEnvelope_AuthResponse
	//	*ServerEnvelope_ChatMessage
	//	*ServerEnvelope_TypingEvent
	//	*ServerEnvelope_Notification
	//	*ServerEnvelope_UnreadCount
	//	*ServerEnvelope_ThreadReply
	//	*ServerEnvelope_AssetUpdated
	//	*ServerEnvelope_Error
	Payload       isServerEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEnvelope) Reset() {
	*x = ServerEnvelope{}
	mi := &file_proto_messaging_ws_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEnvelope) ProtoMessage() {}

func (x *ServerEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_ws_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEnvelope.ProtoReflect.Descriptor instead.
func (*ServerEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_messaging_ws_proto_rawDescGZIP(), []int{5}
}

func (x *ServerEnvelope) GetPayload() isServerEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerEnvelope) GetAuthResponse() *AuthResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_AuthResponse); ok {
			return x.AuthResponse
		}
	}
	return nil
}

func (x *ServerEnvelope) GetChatMessage() *ChatMessage {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_ChatMessage); ok {
			return x.ChatMessage
		}
	}
	return nil
}

func (x *ServerEnvelope) GetTypingEvent() *TypingEvent {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_TypingEvent); ok {
			return x.TypingEvent
		}
	}
	return nil
}

func (x *ServerEnvelope) GetNotification() *NotificationEvent {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_Notification); ok {
			return x.Notification
		}
	}
	return nil
}

func (x *ServerEnvelope) GetUnreadCount() *UnreadCountEvent {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_UnreadCount); ok {
			return x.UnreadCount
		}
	}
	return nil
}

func (x *ServerEnvelope) GetThreadReply() *ThreadReplyEvent {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_ThreadReply); ok {
			return x.ThreadReply
		}
	}
	return nil
}

func (x *ServerEnvelope) GetAssetUpdated() *AssetUpdatedEvent {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_AssetUpdated); ok {
			return x.AssetUpdated
		}
	}
	return nil
}

func (x *ServerEnvelope) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerEnvelope_Payload interface {
	isServerEnvelope_Payload()
}

type ServerEnvelope_AuthResponse struct {
	AuthResponse *AuthResponse `protobuf:"bytes,1,opt,name=auth_response,json=authResponse,proto3,oneof"`
}

type ServerEnvelope_ChatMessage struct {
	ChatMessage *ChatMessage `protobuf:"bytes,2,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

type ServerEnvelope_TypingEvent struct {
	TypingEvent *TypingEvent `protobuf:"bytes,3,opt,name=typing_event,json=typingEvent,proto3,oneof"`
}

type ServerEnvelope_Notification struct {
	Notification *NotificationEvent `protobuf:"bytes,4,opt,name=notification,proto3,oneof"`
}

type ServerEnvelope_UnreadCount struct {
	UnreadCount *UnreadCountEvent `protobuf:"bytes,5,opt,name=unread_count,json=unreadCount,proto3,oneof"`
}

type ServerEnvelope_ThreadReply struct {
	ThreadReply *ThreadReplyEvent `protobuf:"bytes,6,opt,name=thread_reply,json=threadReply,proto3,oneof"`
}

type ServerEnvelope_AssetUpdated struct {
	AssetUpdated *AssetUpdatedEvent `protobuf:"bytes,7,opt,name=asset_updated,json=assetUpdated,proto3,oneof"`
}

type ServerEnvelope_Error struct {
	Error *ErrorEvent `protobuf:"bytes,15,opt,name=error,proto3,oneof"`
}

func (*ServerEnvelope_AuthResponse) isServerEnvelope_Payload() {}

func (*ServerEnvelope_ChatMessage) isServerEnvelope_Payload() {}

func (*ServerEnvelope_TypingEvent) isServerEnvelope_Payload() {}

func (*ServerEnvelope_Notification) isServerEnvelope_Payload() {}

func (*ServerEnvelope_UnreadCount) isServerEnvelope_Payload() {}

func (*ServerEnvelope_ThreadReply) isServerEnvelope_Payload() {}

func (*ServerEnvelope_AssetUpdated) isServerEnvelope_Payload() {}

func (*ServerEnvelope_Error) isServerEnvelope_Payload() {}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_messaging_ws_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_ws_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_messaging_ws_proto_rawDescGZIP(), []int{6}
}

func (x *AuthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ChatMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChannelId       string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SenderId        string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderName      string                 `protobuf:"bytes,4,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Content         string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	MessageType     string                 `protobuf:"bytes,7,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	ParentMessageId string                 `protobuf:"bytes,8,opt,name=parent_message_id,json=parentMessageId,proto3" json:"parent_message_id,omitempty"`
	ReplyCount      int32                  `protobuf:"varint,9,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_messaging_ws_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_ws_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_messaging_ws_proto_rawDescGZIP(), []int{7}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChatMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *ChatMessage) GetParentMessageId() string {
	if x != nil {
		return x.ParentMessageId
	}
	return ""
}

func (x *ChatMessage) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

type TypingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypingEvent) Reset() {
	*x = TypingEvent{}
	mi := &file_proto_messaging_ws_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingEvent) ProtoMessage() {}

func (x *TypingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_ws_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingEvent.ProtoReflect.Descriptor instead.
func (*TypingEvent) Descriptor() ([]byte, []int) {
	return file_proto_messaging_ws_proto_rawDescGZIP(), []int{8}
}

func (x *TypingEvent) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *TypingEvent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type NotificationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	EntityType    string                 `protobuf:"bytes,5,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId      string                 `protobuf:"bytes,6,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationEvent) Reset() {
	*x = NotificationEvent{}
	mi := &file_proto_messaging_ws_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationEvent) ProtoMessage() {}

func (x *NotificationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_ws_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationEvent.ProtoReflect.Descriptor instead.
func (*NotificationEvent) Descriptor() ([]byte, []int) {
	return file_proto_messaging_ws_proto_rawDescGZIP(), []int{9}
}

func (x *NotificationEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationEvent) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NotificationEvent) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *NotificationEvent) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type UnreadCountEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnreadCountEvent) Reset() {
	*x = UnreadCountEvent{}
	mi := &file_proto_messaging_ws_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadCountEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadCountEvent) ProtoMessage() {}

func (x *UnreadCountEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_ws_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadCountEvent.ProtoReflect.Descriptor instead.
func (*UnreadCountEvent) Descriptor() ([]byte, []int) {
	return file_proto_messaging_ws_proto_rawDescGZIP(), []int{10}
}

func (x *UnreadCountEvent) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ThreadReplyEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Message         *ChatMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ParentMessageId string                 `protobuf:"bytes,2,opt,name=parent_message_id,json=parentMessageId,proto3" json:"parent_message_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ThreadReplyEvent) Reset() {
	*x = ThreadReplyEvent{}
	mi := &file_proto_messaging_ws_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadReplyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadReplyEvent) ProtoMessage() {}

func (x *ThreadReplyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_ws_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadReplyEvent.ProtoReflect.Descriptor instead.
func (*ThreadReplyEvent) Descriptor() ([]byte, []int) {
	return file_proto_messaging_ws_proto_rawDescGZIP(), []int{11}
}

func (x *ThreadReplyEvent) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ThreadReplyEvent) GetParentMessageId() string {
	if x != nil {
		return x.ParentMessageId
	}
	return ""
}

type AssetUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	NewState      string                 `protobuf:"bytes,2,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetUpdatedEvent) Reset() {
	*x = AssetUpdatedEvent{}
	mi := &file_proto_messaging_ws_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetUpdatedEvent) ProtoMessage() {}

func (x *AssetUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_ws_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetUpdatedEvent.ProtoReflect.Descriptor instead.
func (*AssetUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_proto_messaging_ws_proto_rawDescGZIP(), []int{12}
}

func (x *AssetUpdatedEvent) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetUpdatedEvent) GetNewState() string {
	if x != nil {
		return x.NewState
	}
	return ""
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_proto_messaging_ws_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messaging_ws_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_proto_messaging_ws_proto_rawDescGZIP(), []int{13}
}

func (x *ErrorEvent) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_messaging_ws_proto protoreflect.FileDescriptor

const file_proto_messaging_ws_proto_rawDesc = "" +
	"\n" +
	"\x18proto/messaging/ws.proto\x12\tmessaging\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfd\x01\n" +
	"\x0eClientEnvelope\x12,\n" +
	"\x04auth\x18\x01 \x01(\v2\x16.messaging.AuthRequestH\x00R\x04auth\x12;\n" +
	"\tsubscribe\x18\x02 \x01(\v2\x1b.messaging.SubscribeRequestH\x00R\tsubscribe\x12A\n" +
	"\vunsubscribe\x18\x03 \x01(\v2\x1d.messaging.UnsubscribeRequestH\x00R\vunsubscribe\x122\n" +
	"\x06typing\x18\x04 \x01(\v2\x18.messaging.TypingRequestH\x00R\x06typingB\t\n" +
	"\apayload\"#\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"1\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"3\n" +
	"\x12UnsubscribeRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\".\n" +
	"\rTypingRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"\x91\x04\n" +
	"\x0eServerEnvelope\x12>\n" +
	"\rauth_response\x18\x01 \x01(\v2\x17.messaging.AuthResponseH\x00R\fauthResponse\x12;\n" +
	"\fchat_message\x18\x02 \x01(\v2\x16.messaging.ChatMessageH\x00R\vchatMessage\x12;\n" +
	"\ftyping_event\x18\x03 \x01(\v2\x16.messaging.TypingEventH\x00R\vtypingEvent\x12B\n" +
	"\fnotification\x18\x04 \x01(\v2\x1c.messaging.NotificationEventH\x00R\fnotification\x12@\n" +
	"\funread_count\x18\x05 \x01(\v2\x1b.messaging.UnreadCountEventH\x00R\vunreadCount\x12@\n" +
	"\fthread_reply\x18\x06 \x01(\v2\x1b.messaging.ThreadReplyEventH\x00R\vthreadReply\x12C\n" +
	"\rasset_updated\x18\a \x01(\v2\x1c.messaging.AssetUpdatedEventH\x00R\fassetUpdated\x12-\n" +
	"\x05error\x18\x0f \x01(\v2\x15.messaging.ErrorEventH\x00R\x05errorB\t\n" +
	"\apayload\"O\n" +
	"\fAuthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xbf\x02\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\x04 \x01(\tR\n" +
	"senderName\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12!\n" +
	"\fmessage_type\x18\a \x01(\tR\vmessageType\x12*\n" +
	"\x11parent_message_id\x18\b \x01(\tR\x0fparentMessageId\x12\x1f\n" +
	"\vreply_count\x18\t \x01(\x05R\n" +
	"replyCount\"H\n" +
	"\vTypingEvent\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\x9f\x01\n" +
	"\x11NotificationEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1f\n" +
	"\ventity_type\x18\x05 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x06 \x01(\tR\bentityId\"(\n" +
	"\x10UnreadCountEvent\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"p\n" +
	"\x10ThreadReplyEvent\x120\n" +
	"\amessage\x18\x01 \x01(\v2\x16.messaging.ChatMessageR\amessage\x12*\n" +
	"\x11parent_message_id\x18\x02 \x01(\tR\x0fparentMessageId\"K\n" +
	"\x11AssetUpdatedEvent\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x1b\n" +
	"\tnew_state\x18\x02 \x01(\tR\bnewState\":\n" +
	"\n" +
	"ErrorEvent\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\x1fZ\x1dngac-platform/proto/messagingb\x06proto3"

var (
	file_proto_messaging_ws_proto_rawDescOnce sync.Once
	file_proto_messaging_ws_proto_rawDescData []byte
)

func file_proto_messaging_ws_proto_rawDescGZIP() []byte {
	file_proto_messaging_ws_proto_rawDescOnce.Do(func() {
		file_proto_messaging_ws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messaging_ws_proto_rawDesc), len(file_proto_messaging_ws_proto_rawDesc)))
	})
	return file_proto_messaging_ws_proto_rawDescData
}

var file_proto_messaging_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_messaging_ws_proto_goTypes = []any{
	(*ClientEnvelope)(nil),        // 0: messaging.ClientEnvelope
	(*AuthRequest)(nil),           // 1: messaging.AuthRequest
	(*SubscribeRequest)(nil),      // 2: messaging.SubscribeRequest
	(*UnsubscribeRequest)(nil),    // 3: messaging.UnsubscribeRequest
	(*TypingRequest)(nil),         // 4: messaging.TypingRequest
	(*ServerEnvelope)(nil),        // 5: messaging.ServerEnvelope
	(*AuthResponse)(nil),          // 6: messaging.AuthResponse
	(*ChatMessage)(nil),           // 7: messaging.ChatMessage
	(*TypingEvent)(nil),           // 8: messaging.TypingEvent
	(*NotificationEvent)(nil),     // 9: messaging.NotificationEvent
	(*UnreadCountEvent)(nil),      // 10: messaging.UnreadCountEvent
	(*ThreadReplyEvent)(nil),      // 11: messaging.ThreadReplyEvent
	(*AssetUpdatedEvent)(nil),     // 12: messaging.AssetUpdatedEvent
	(*ErrorEvent)(nil),            // 13: messaging.ErrorEvent
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_proto_messaging_ws_proto_depIdxs = []int32{
	1,  // 0: messaging.ClientEnvelope.auth:type_name -> messaging.AuthRequest
	2,  // 1: messaging.ClientEnvelope.subscribe:type_name -> messaging.SubscribeRequest
	3,  // 2: messaging.ClientEnvelope.unsubscribe:type_name -> messaging.UnsubscribeRequest
	4,  // 3: messaging.ClientEnvelope.typing:type_name -> messaging.TypingRequest
	6,  // 4: messaging.ServerEnvelope.auth_response:type_name -> messaging.AuthResponse
	7,  // 5: messaging.ServerEnvelope.chat_message:type_name -> messaging.ChatMessage
	8,  // 6: messaging.ServerEnvelope.typing_event:type_name -> messaging.TypingEvent
	9,  // 7: messaging.ServerEnvelope.notification:type_name -> messaging.NotificationEvent
	10, // 8: messaging.ServerEnvelope.unread_count:type_name -> messaging.UnreadCountEvent
	11, // 9: messaging.ServerEnvelope.thread_reply:type_name -> messaging.ThreadReplyEvent
	12, // 10: messaging.ServerEnvelope.asset_updated:type_name -> messaging.AssetUpdatedEvent
	13, // 11: messaging.ServerEnvelope.error:type_name -> messaging.ErrorEvent
	14, // 12: messaging.ChatMessage.created_at:type_name -> google.protobuf.Timestamp
	7,  // 13: messaging.ThreadReplyEvent.message:type_name -> messaging.ChatMessage
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_messaging_ws_proto_init() }
func file_proto_messaging_ws_proto_init() {
	if File_proto_messaging_ws_proto != nil {
		return
	}
	file_proto_messaging_ws_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientEnvelope_Auth)(nil),
		(*ClientEnvelope_Subscribe)(nil),
		(*ClientEnvelope_Unsubscribe)(nil),
		(*ClientEnvelope_Typing)(nil),
	}
	file_proto_messaging_ws_proto_msgTypes[5].OneofWrappers = []any{
		(*ServerEnvelope_AuthResponse)(nil),
		(*ServerEnvelope_ChatMessage)(nil),
		(*ServerEnvelope_TypingEvent)(nil),
		(*ServerEnvelope_Notification)(nil),
		(*ServerEnvelope_UnreadCount)(nil),
		(*ServerEnvelope_ThreadReply)(nil),
		(*ServerEnvelope_AssetUpdated)(nil),
		(*ServerEnvelope_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messaging_ws_proto_rawDesc), len(file_proto_messaging_ws_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_messaging_ws_proto_goTypes,
		DependencyIndexes: file_proto_messaging_ws_proto_depIdxs,
		MessageInfos:      file_proto_messaging_ws_proto_msgTypes,
	}.Build()
	File_proto_messaging_ws_proto = out.File
	file_proto_messaging_ws_proto_goTypes = nil
	file_proto_messaging_ws_proto_depIdxs = nil
}
