// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/asset/asset_request.proto

package asset

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssetRequestService_CreateRequest_FullMethodName  = "/asset.AssetRequestService/CreateRequest"
	AssetRequestService_ApproveRequest_FullMethodName = "/asset.AssetRequestService/ApproveRequest"
	AssetRequestService_RejectRequest_FullMethodName  = "/asset.AssetRequestService/RejectRequest"
	AssetRequestService_AssignAsset_FullMethodName    = "/asset.AssetRequestService/AssignAsset"
	AssetRequestService_ReturnAsset_FullMethodName    = "/asset.AssetRequestService/ReturnAsset"
	AssetRequestService_ListRequests_FullMethodName   = "/asset.AssetRequestService/ListRequests"
	AssetRequestService_GetRequest_FullMethodName     = "/asset.AssetRequestService/GetRequest"
)

// AssetRequestServiceClient is the client API for AssetRequestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetRequestServiceClient interface {
	CreateRequest(ctx context.Context, in *CreateAssetRequestReq, opts ...grpc.CallOption) (*AssetRequest, error)
	ApproveRequest(ctx context.Context, in *ApproveRequestReq, opts ...grpc.CallOption) (*AssetRequest, error)
	RejectRequest(ctx context.Context, in *RejectRequestReq, opts ...grpc.CallOption) (*AssetRequest, error)
	AssignAsset(ctx context.Context, in *AssignAssetReq, opts ...grpc.CallOption) (*AssetRequest, error)
	ReturnAsset(ctx context.Context, in *ReturnAssetReq, opts ...grpc.CallOption) (*Empty, error)
	ListRequests(ctx context.Context, in *ListRequestsReq, opts ...grpc.CallOption) (*AssetRequestList, error)
	GetRequest(ctx context.Context, in *GetRequestReq, opts ...grpc.CallOption) (*AssetRequest, error)
}

type assetRequestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetRequestServiceClient(cc grpc.ClientConnInterface) AssetRequestServiceClient {
	return &assetRequestServiceClient{cc}
}

func (c *assetRequestServiceClient) CreateRequest(ctx context.Context, in *CreateAssetRequestReq, opts ...grpc.CallOption) (*AssetRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetRequest)
	err := c.cc.Invoke(ctx, AssetRequestService_CreateRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetRequestServiceClient) ApproveRequest(ctx context.Context, in *ApproveRequestReq, opts ...grpc.CallOption) (*AssetRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetRequest)
	err := c.cc.Invoke(ctx, AssetRequestService_ApproveRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetRequestServiceClient) RejectRequest(ctx context.Context, in *RejectRequestReq, opts ...grpc.CallOption) (*AssetRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetRequest)
	err := c.cc.Invoke(ctx, AssetRequestService_RejectRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetRequestServiceClient) AssignAsset(ctx context.Context, in *AssignAssetReq, opts ...grpc.CallOption) (*AssetRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetRequest)
	err := c.cc.Invoke(ctx, AssetRequestService_AssignAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetRequestServiceClient) ReturnAsset(ctx context.Context, in *ReturnAssetReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AssetRequestService_ReturnAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetRequestServiceClient) ListRequests(ctx context.Context, in *ListRequestsReq, opts ...grpc.CallOption) (*AssetRequestList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetRequestList)
	err := c.cc.Invoke(ctx, AssetRequestService_ListRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetRequestServiceClient) GetRequest(ctx context.Context, in *GetRequestReq, opts ...grpc.CallOption) (*AssetRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetRequest)
	err := c.cc.Invoke(ctx, AssetRequestService_GetRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetRequestServiceServer is the server API for AssetRequestService service.
// All implementations must embed UnimplementedAssetRequestServiceServer
// for forward compatibility.
type AssetRequestServiceServer interface {
	CreateRequest(context.Context, *CreateAssetRequestReq) (*AssetRequest, error)
	ApproveRequest(context.Context, *ApproveRequestReq) (*AssetRequest, error)
	RejectRequest(context.Context, *RejectRequestReq) (*AssetRequest, error)
	AssignAsset(context.Context, *AssignAssetReq) (*AssetRequest, error)
	ReturnAsset(context.Context, *ReturnAssetReq) (*Empty, error)
	ListRequests(context.Context, *ListRequestsReq) (*AssetRequestList, error)
	GetRequest(context.Context, *GetRequestReq) (*AssetRequest, error)
	mustEmbedUnimplementedAssetRequestServiceServer()
}

// UnimplementedAssetRequestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssetRequestServiceServer struct{}

func (UnimplementedAssetRequestServiceServer) CreateRequest(context.Context, *CreateAssetRequestReq) (*AssetRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRequest not implemented")
}
func (UnimplementedAssetRequestServiceServer) ApproveRequest(context.Context, *ApproveRequestReq) (*AssetRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveRequest not implemented")
}
func (UnimplementedAssetRequestServiceServer) RejectRequest(context.Context, *RejectRequestReq) (*AssetRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectRequest not implemented")
}
func (UnimplementedAssetRequestServiceServer) AssignAsset(context.Context, *AssignAssetReq) (*AssetRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignAsset not implemented")
}
func (UnimplementedAssetRequestServiceServer) ReturnAsset(context.Context, *ReturnAssetReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReturnAsset not implemented")
}
func (UnimplementedAssetRequestServiceServer) ListRequests(context.Context, *ListRequestsReq) (*AssetRequestList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRequests not implemented")
}
func (UnimplementedAssetRequestServiceServer) GetRequest(context.Context, *GetRequestReq) (*AssetRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRequest not implemented")
}
func (UnimplementedAssetRequestServiceServer) mustEmbedUnimplementedAssetRequestServiceServer() {}
func (UnimplementedAssetRequestServiceServer) testEmbeddedByValue()                             {}

// UnsafeAssetRequestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetRequestServiceServer will
// result in compilation errors.
type UnsafeAssetRequestServiceServer interface {
	mustEmbedUnimplementedAssetRequestServiceServer()
}

func RegisterAssetRequestServiceServer(s grpc.ServiceRegistrar, srv AssetRequestServiceServer) {
	// If the following call panics, it indicates UnimplementedAssetRequestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssetRequestService_ServiceDesc, srv)
}

func _AssetRequestService_CreateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssetRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetRequestServiceServer).CreateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetRequestService_CreateRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetRequestServiceServer).CreateRequest(ctx, req.(*CreateAssetRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetRequestService_ApproveRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetRequestServiceServer).ApproveRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetRequestService_ApproveRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetRequestServiceServer).ApproveRequest(ctx, req.(*ApproveRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetRequestService_RejectRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetRequestServiceServer).RejectRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetRequestService_RejectRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetRequestServiceServer).RejectRequest(ctx, req.(*RejectRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetRequestService_AssignAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignAssetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetRequestServiceServer).AssignAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetRequestService_AssignAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetRequestServiceServer).AssignAsset(ctx, req.(*AssignAssetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetRequestService_ReturnAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnAssetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetRequestServiceServer).ReturnAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetRequestService_ReturnAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetRequestServiceServer).ReturnAsset(ctx, req.(*ReturnAssetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetRequestService_ListRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequestsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetRequestServiceServer).ListRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetRequestService_ListRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetRequestServiceServer).ListRequests(ctx, req.(*ListRequestsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetRequestService_GetRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetRequestServiceServer).GetRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetRequestService_GetRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetRequestServiceServer).GetRequest(ctx, req.(*GetRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetRequestService_ServiceDesc is the grpc.ServiceDesc for AssetRequestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetRequestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asset.AssetRequestService",
	HandlerType: (*AssetRequestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRequest",
			Handler:    _AssetRequestService_CreateRequest_Handler,
		},
		{
			MethodName: "ApproveRequest",
			Handler:    _AssetRequestService_ApproveRequest_Handler,
		},
		{
			MethodName: "RejectRequest",
			Handler:    _AssetRequestService_RejectRequest_Handler,
		},
		{
			MethodName: "AssignAsset",
			Handler:    _AssetRequestService_AssignAsset_Handler,
		},
		{
			MethodName: "ReturnAsset",
			Handler:    _AssetRequestService_ReturnAsset_Handler,
		},
		{
			MethodName: "ListRequests",
			Handler:    _AssetRequestService_ListRequests_Handler,
		},
		{
			MethodName: "GetRequest",
			Handler:    _AssetRequestService_GetRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/asset/asset_request.proto",
}
