// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/asset/asset.proto

package asset

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssetTypeService_CreateType_FullMethodName       = "/asset.AssetTypeService/CreateType"
	AssetTypeService_GetType_FullMethodName          = "/asset.AssetTypeService/GetType"
	AssetTypeService_ListTypes_FullMethodName        = "/asset.AssetTypeService/ListTypes"
	AssetTypeService_UpdateTypeSchema_FullMethodName = "/asset.AssetTypeService/UpdateTypeSchema"
)

// AssetTypeServiceClient is the client API for AssetTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AssetTypeService manages dynamic asset type definitions with custom fields and lifecycle.
type AssetTypeServiceClient interface {
	CreateType(ctx context.Context, in *CreateTypeRequest, opts ...grpc.CallOption) (*AssetType, error)
	GetType(ctx context.Context, in *GetTypeRequest, opts ...grpc.CallOption) (*AssetType, error)
	ListTypes(ctx context.Context, in *ListTypesRequest, opts ...grpc.CallOption) (*AssetTypeList, error)
	UpdateTypeSchema(ctx context.Context, in *UpdateTypeSchemaRequest, opts ...grpc.CallOption) (*AssetType, error)
}

type assetTypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetTypeServiceClient(cc grpc.ClientConnInterface) AssetTypeServiceClient {
	return &assetTypeServiceClient{cc}
}

func (c *assetTypeServiceClient) CreateType(ctx context.Context, in *CreateTypeRequest, opts ...grpc.CallOption) (*AssetType, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetType)
	err := c.cc.Invoke(ctx, AssetTypeService_CreateType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetTypeServiceClient) GetType(ctx context.Context, in *GetTypeRequest, opts ...grpc.CallOption) (*AssetType, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetType)
	err := c.cc.Invoke(ctx, AssetTypeService_GetType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetTypeServiceClient) ListTypes(ctx context.Context, in *ListTypesRequest, opts ...grpc.CallOption) (*AssetTypeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetTypeList)
	err := c.cc.Invoke(ctx, AssetTypeService_ListTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetTypeServiceClient) UpdateTypeSchema(ctx context.Context, in *UpdateTypeSchemaRequest, opts ...grpc.CallOption) (*AssetType, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetType)
	err := c.cc.Invoke(ctx, AssetTypeService_UpdateTypeSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetTypeServiceServer is the server API for AssetTypeService service.
// All implementations must embed UnimplementedAssetTypeServiceServer
// for forward compatibility.
//
// AssetTypeService manages dynamic asset type definitions with custom fields and lifecycle.
type AssetTypeServiceServer interface {
	CreateType(context.Context, *CreateTypeRequest) (*AssetType, error)
	GetType(context.Context, *GetTypeRequest) (*AssetType, error)
	ListTypes(context.Context, *ListTypesRequest) (*AssetTypeList, error)
	UpdateTypeSchema(context.Context, *UpdateTypeSchemaRequest) (*AssetType, error)
	mustEmbedUnimplementedAssetTypeServiceServer()
}

// UnimplementedAssetTypeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssetTypeServiceServer struct{}

func (UnimplementedAssetTypeServiceServer) CreateType(context.Context, *CreateTypeRequest) (*AssetType, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateType not implemented")
}
func (UnimplementedAssetTypeServiceServer) GetType(context.Context, *GetTypeRequest) (*AssetType, error) {
	return nil, status.Error(codes.Unimplemented, "method GetType not implemented")
}
func (UnimplementedAssetTypeServiceServer) ListTypes(context.Context, *ListTypesRequest) (*AssetTypeList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTypes not implemented")
}
func (UnimplementedAssetTypeServiceServer) UpdateTypeSchema(context.Context, *UpdateTypeSchemaRequest) (*AssetType, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTypeSchema not implemented")
}
func (UnimplementedAssetTypeServiceServer) mustEmbedUnimplementedAssetTypeServiceServer() {}
func (UnimplementedAssetTypeServiceServer) testEmbeddedByValue()                          {}

// UnsafeAssetTypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetTypeServiceServer will
// result in compilation errors.
type UnsafeAssetTypeServiceServer interface {
	mustEmbedUnimplementedAssetTypeServiceServer()
}

func RegisterAssetTypeServiceServer(s grpc.ServiceRegistrar, srv AssetTypeServiceServer) {
	// If the following call panics, it indicates UnimplementedAssetTypeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssetTypeService_ServiceDesc, srv)
}

func _AssetTypeService_CreateType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetTypeServiceServer).CreateType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetTypeService_CreateType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetTypeServiceServer).CreateType(ctx, req.(*CreateTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetTypeService_GetType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetTypeServiceServer).GetType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetTypeService_GetType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetTypeServiceServer).GetType(ctx, req.(*GetTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetTypeService_ListTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetTypeServiceServer).ListTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetTypeService_ListTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetTypeServiceServer).ListTypes(ctx, req.(*ListTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetTypeService_UpdateTypeSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTypeSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetTypeServiceServer).UpdateTypeSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetTypeService_UpdateTypeSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetTypeServiceServer).UpdateTypeSchema(ctx, req.(*UpdateTypeSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetTypeService_ServiceDesc is the grpc.ServiceDesc for AssetTypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetTypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asset.AssetTypeService",
	HandlerType: (*AssetTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateType",
			Handler:    _AssetTypeService_CreateType_Handler,
		},
		{
			MethodName: "GetType",
			Handler:    _AssetTypeService_GetType_Handler,
		},
		{
			MethodName: "ListTypes",
			Handler:    _AssetTypeService_ListTypes_Handler,
		},
		{
			MethodName: "UpdateTypeSchema",
			Handler:    _AssetTypeService_UpdateTypeSchema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/asset/asset.proto",
}

const (
	AssetService_CreateAsset_FullMethodName             = "/asset.AssetService/CreateAsset"
	AssetService_GetAsset_FullMethodName                = "/asset.AssetService/GetAsset"
	AssetService_ListAssets_FullMethodName              = "/asset.AssetService/ListAssets"
	AssetService_UpdateAsset_FullMethodName             = "/asset.AssetService/UpdateAsset"
	AssetService_DeleteAsset_FullMethodName             = "/asset.AssetService/DeleteAsset"
	AssetService_TransitionAsset_FullMethodName         = "/asset.AssetService/TransitionAsset"
	AssetService_GetAvailableTransitions_FullMethodName = "/asset.AssetService/GetAvailableTransitions"
	AssetService_GetAssetHistory_FullMethodName         = "/asset.AssetService/GetAssetHistory"
)

// AssetServiceClient is the client API for AssetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AssetService manages asset instances — CRUD, lifecycle transitions, and history.
type AssetServiceClient interface {
	CreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...grpc.CallOption) (*Asset, error)
	GetAsset(ctx context.Context, in *GetAssetRequest, opts ...grpc.CallOption) (*Asset, error)
	ListAssets(ctx context.Context, in *ListAssetsRequest, opts ...grpc.CallOption) (*AssetList, error)
	UpdateAsset(ctx context.Context, in *UpdateAssetRequest, opts ...grpc.CallOption) (*Asset, error)
	DeleteAsset(ctx context.Context, in *DeleteAssetRequest, opts ...grpc.CallOption) (*Empty, error)
	// Lifecycle
	TransitionAsset(ctx context.Context, in *TransitionRequest, opts ...grpc.CallOption) (*Asset, error)
	GetAvailableTransitions(ctx context.Context, in *GetTransitionsRequest, opts ...grpc.CallOption) (*TransitionList, error)
	GetAssetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*TransitionHistoryList, error)
}

type assetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetServiceClient(cc grpc.ClientConnInterface) AssetServiceClient {
	return &assetServiceClient{cc}
}

func (c *assetServiceClient) CreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetService_CreateAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetAsset(ctx context.Context, in *GetAssetRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetService_GetAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) ListAssets(ctx context.Context, in *ListAssetsRequest, opts ...grpc.CallOption) (*AssetList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetList)
	err := c.cc.Invoke(ctx, AssetService_ListAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) UpdateAsset(ctx context.Context, in *UpdateAssetRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetService_UpdateAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) DeleteAsset(ctx context.Context, in *DeleteAssetRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AssetService_DeleteAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) TransitionAsset(ctx context.Context, in *TransitionRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetService_TransitionAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetAvailableTransitions(ctx context.Context, in *GetTransitionsRequest, opts ...grpc.CallOption) (*TransitionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransitionList)
	err := c.cc.Invoke(ctx, AssetService_GetAvailableTransitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetAssetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*TransitionHistoryList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransitionHistoryList)
	err := c.cc.Invoke(ctx, AssetService_GetAssetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetServiceServer is the server API for AssetService service.
// All implementations must embed UnimplementedAssetServiceServer
// for forward compatibility.
//
// AssetService manages asset instances — CRUD, lifecycle transitions, and history.
type AssetServiceServer interface {
	CreateAsset(context.Context, *CreateAssetRequest) (*Asset, error)
	GetAsset(context.Context, *GetAssetRequest) (*Asset, error)
	ListAssets(context.Context, *ListAssetsRequest) (*AssetList, error)
	UpdateAsset(context.Context, *UpdateAssetRequest) (*Asset, error)
	DeleteAsset(context.Context, *DeleteAssetRequest) (*Empty, error)
	// Lifecycle
	TransitionAsset(context.Context, *TransitionRequest) (*Asset, error)
	GetAvailableTransitions(context.Context, *GetTransitionsRequest) (*TransitionList, error)
	GetAssetHistory(context.Context, *GetHistoryRequest) (*TransitionHistoryList, error)
	mustEmbedUnimplementedAssetServiceServer()
}

// UnimplementedAssetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssetServiceServer struct{}

func (UnimplementedAssetServiceServer) CreateAsset(context.Context, *CreateAssetRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAsset not implemented")
}
func (UnimplementedAssetServiceServer) GetAsset(context.Context, *GetAssetRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAsset not implemented")
}
func (UnimplementedAssetServiceServer) ListAssets(context.Context, *ListAssetsRequest) (*AssetList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAssets not implemented")
}
func (UnimplementedAssetServiceServer) UpdateAsset(context.Context, *UpdateAssetRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAsset not implemented")
}
func (UnimplementedAssetServiceServer) DeleteAsset(context.Context, *DeleteAssetRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAsset not implemented")
}
func (UnimplementedAssetServiceServer) TransitionAsset(context.Context, *TransitionRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method TransitionAsset not implemented")
}
func (UnimplementedAssetServiceServer) GetAvailableTransitions(context.Context, *GetTransitionsRequest) (*TransitionList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableTransitions not implemented")
}
func (UnimplementedAssetServiceServer) GetAssetHistory(context.Context, *GetHistoryRequest) (*TransitionHistoryList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssetHistory not implemented")
}
func (UnimplementedAssetServiceServer) mustEmbedUnimplementedAssetServiceServer() {}
func (UnimplementedAssetServiceServer) testEmbeddedByValue()                      {}

// UnsafeAssetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetServiceServer will
// result in compilation errors.
type UnsafeAssetServiceServer interface {
	mustEmbedUnimplementedAssetServiceServer()
}

func RegisterAssetServiceServer(s grpc.ServiceRegistrar, srv AssetServiceServer) {
	// If the following call panics, it indicates UnimplementedAssetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssetService_ServiceDesc, srv)
}

func _AssetService_CreateAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).CreateAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_CreateAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).CreateAsset(ctx, req.(*CreateAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetAsset(ctx, req.(*GetAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_ListAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).ListAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_ListAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).ListAssets(ctx, req.(*ListAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_UpdateAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).UpdateAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_UpdateAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).UpdateAsset(ctx, req.(*UpdateAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_DeleteAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).DeleteAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_DeleteAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).DeleteAsset(ctx, req.(*DeleteAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_TransitionAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).TransitionAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_TransitionAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).TransitionAsset(ctx, req.(*TransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetAvailableTransitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetAvailableTransitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetAvailableTransitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetAvailableTransitions(ctx, req.(*GetTransitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetAssetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetAssetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetAssetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetAssetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetService_ServiceDesc is the grpc.ServiceDesc for AssetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asset.AssetService",
	HandlerType: (*AssetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAsset",
			Handler:    _AssetService_CreateAsset_Handler,
		},
		{
			MethodName: "GetAsset",
			Handler:    _AssetService_GetAsset_Handler,
		},
		{
			MethodName: "ListAssets",
			Handler:    _AssetService_ListAssets_Handler,
		},
		{
			MethodName: "UpdateAsset",
			Handler:    _AssetService_UpdateAsset_Handler,
		},
		{
			MethodName: "DeleteAsset",
			Handler:    _AssetService_DeleteAsset_Handler,
		},
		{
			MethodName: "TransitionAsset",
			Handler:    _AssetService_TransitionAsset_Handler,
		},
		{
			MethodName: "GetAvailableTransitions",
			Handler:    _AssetService_GetAvailableTransitions_Handler,
		},
		{
			MethodName: "GetAssetHistory",
			Handler:    _AssetService_GetAssetHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/asset/asset.proto",
}
