// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/asset/asset_request.proto

package asset

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId          string                 `protobuf:"bytes,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	TypeName        string                 `protobuf:"bytes,3,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	WorkspaceId     string                 `protobuf:"bytes,4,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	RequesterId     string                 `protobuf:"bytes,5,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	RequesterName   string                 `protobuf:"bytes,6,opt,name=requester_name,json=requesterName,proto3" json:"requester_name,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // "pending", "approved", "rejected", "fulfilled"
	Justification   string                 `protobuf:"bytes,8,opt,name=justification,proto3" json:"justification,omitempty"`
	Quantity        int32                  `protobuf:"varint,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	AssignedAssetId string                 `protobuf:"bytes,10,opt,name=assigned_asset_id,json=assignedAssetId,proto3" json:"assigned_asset_id,omitempty"`
	ApproverId      string                 `protobuf:"bytes,11,opt,name=approver_id,json=approverId,proto3" json:"approver_id,omitempty"`
	ApproverName    string                 `protobuf:"bytes,12,opt,name=approver_name,json=approverName,proto3" json:"approver_name,omitempty"`
	ApproverComment string                 `protobuf:"bytes,13,opt,name=approver_comment,json=approverComment,proto3" json:"approver_comment,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssetRequest) Reset() {
	*x = AssetRequest{}
	mi := &file_proto_asset_asset_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetRequest) ProtoMessage() {}

func (x *AssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetRequest.ProtoReflect.Descriptor instead.
func (*AssetRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_request_proto_rawDescGZIP(), []int{0}
}

func (x *AssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AssetRequest) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *AssetRequest) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *AssetRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *AssetRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *AssetRequest) GetRequesterName() string {
	if x != nil {
		return x.RequesterName
	}
	return ""
}

func (x *AssetRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AssetRequest) GetJustification() string {
	if x != nil {
		return x.Justification
	}
	return ""
}

func (x *AssetRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AssetRequest) GetAssignedAssetId() string {
	if x != nil {
		return x.AssignedAssetId
	}
	return ""
}

func (x *AssetRequest) GetApproverId() string {
	if x != nil {
		return x.ApproverId
	}
	return ""
}

func (x *AssetRequest) GetApproverName() string {
	if x != nil {
		return x.ApproverName
	}
	return ""
}

func (x *AssetRequest) GetApproverComment() string {
	if x != nil {
		return x.ApproverComment
	}
	return ""
}

func (x *AssetRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AssetRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateAssetRequestReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TypeId         string                 `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	WorkspaceId    string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserNgacNodeId string                 `protobuf:"bytes,4,opt,name=user_ngac_node_id,json=userNgacNodeId,proto3" json:"user_ngac_node_id,omitempty"`
	Justification  string                 `protobuf:"bytes,5,opt,name=justification,proto3" json:"justification,omitempty"`
	Quantity       int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAssetRequestReq) Reset() {
	*x = CreateAssetRequestReq{}
	mi := &file_proto_asset_asset_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetRequestReq) ProtoMessage() {}

func (x *CreateAssetRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetRequestReq.ProtoReflect.Descriptor instead.
func (*CreateAssetRequestReq) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_request_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAssetRequestReq) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *CreateAssetRequestReq) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateAssetRequestReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAssetRequestReq) GetUserNgacNodeId() string {
	if x != nil {
		return x.UserNgacNodeId
	}
	return ""
}

func (x *CreateAssetRequestReq) GetJustification() string {
	if x != nil {
		return x.Justification
	}
	return ""
}

func (x *CreateAssetRequestReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ApproveRequestReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserNgacNodeId string                 `protobuf:"bytes,3,opt,name=user_ngac_node_id,json=userNgacNodeId,proto3" json:"user_ngac_node_id,omitempty"`
	Comment        string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApproveRequestReq) Reset() {
	*x = ApproveRequestReq{}
	mi := &file_proto_asset_asset_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequestReq) ProtoMessage() {}

func (x *ApproveRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequestReq.ProtoReflect.Descriptor instead.
func (*ApproveRequestReq) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_request_proto_rawDescGZIP(), []int{2}
}

func (x *ApproveRequestReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApproveRequestReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ApproveRequestReq) GetUserNgacNodeId() string {
	if x != nil {
		return x.UserNgacNodeId
	}
	return ""
}

func (x *ApproveRequestReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type RejectRequestReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserNgacNodeId string                 `protobuf:"bytes,3,opt,name=user_ngac_node_id,json=userNgacNodeId,proto3" json:"user_ngac_node_id,omitempty"`
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RejectRequestReq) Reset() {
	*x = RejectRequestReq{}
	mi := &file_proto_asset_asset_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequestReq) ProtoMessage() {}

func (x *RejectRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequestReq.ProtoReflect.Descriptor instead.
func (*RejectRequestReq) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_request_proto_rawDescGZIP(), []int{3}
}

func (x *RejectRequestReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RejectRequestReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RejectRequestReq) GetUserNgacNodeId() string {
	if x != nil {
		return x.UserNgacNodeId
	}
	return ""
}

func (x *RejectRequestReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AssignAssetReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AssetId        string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserNgacNodeId string                 `protobuf:"bytes,4,opt,name=user_ngac_node_id,json=userNgacNodeId,proto3" json:"user_ngac_node_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssignAssetReq) Reset() {
	*x = AssignAssetReq{}
	mi := &file_proto_asset_asset_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAssetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAssetReq) ProtoMessage() {}

func (x *AssignAssetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAssetReq.ProtoReflect.Descriptor instead.
func (*AssignAssetReq) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_request_proto_rawDescGZIP(), []int{4}
}

func (x *AssignAssetReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AssignAssetReq) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssignAssetReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignAssetReq) GetUserNgacNodeId() string {
	if x != nil {
		return x.UserNgacNodeId
	}
	return ""
}

type ReturnAssetReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AssetId        string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserNgacNodeId string                 `protobuf:"bytes,3,opt,name=user_ngac_node_id,json=userNgacNodeId,proto3" json:"user_ngac_node_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReturnAssetReq) Reset() {
	*x = ReturnAssetReq{}
	mi := &file_proto_asset_asset_request_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnAssetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnAssetReq) ProtoMessage() {}

func (x *ReturnAssetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_request_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnAssetReq.ProtoReflect.Descriptor instead.
func (*ReturnAssetReq) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_request_proto_rawDescGZIP(), []int{5}
}

func (x *ReturnAssetReq) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ReturnAssetReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReturnAssetReq) GetUserNgacNodeId() string {
	if x != nil {
		return x.UserNgacNodeId
	}
	return ""
}

type ListRequestsReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId    string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserNgacNodeId string                 `protobuf:"bytes,3,opt,name=user_ngac_node_id,json=userNgacNodeId,proto3" json:"user_ngac_node_id,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                      // Optional filter
	MineOnly       bool                   `protobuf:"varint,5,opt,name=mine_only,json=mineOnly,proto3" json:"mine_only,omitempty"` // If true, only return user's own requests
	Limit          int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListRequestsReq) Reset() {
	*x = ListRequestsReq{}
	mi := &file_proto_asset_asset_request_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsReq) ProtoMessage() {}

func (x *ListRequestsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_request_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsReq.ProtoReflect.Descriptor instead.
func (*ListRequestsReq) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_request_proto_rawDescGZIP(), []int{6}
}

func (x *ListRequestsReq) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListRequestsReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListRequestsReq) GetUserNgacNodeId() string {
	if x != nil {
		return x.UserNgacNodeId
	}
	return ""
}

func (x *ListRequestsReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListRequestsReq) GetMineOnly() bool {
	if x != nil {
		return x.MineOnly
	}
	return false
}

func (x *ListRequestsReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequestsReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetRequestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestReq) Reset() {
	*x = GetRequestReq{}
	mi := &file_proto_asset_asset_request_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestReq) ProtoMessage() {}

func (x *GetRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_request_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestReq.ProtoReflect.Descriptor instead.
func (*GetRequestReq) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_request_proto_rawDescGZIP(), []int{7}
}

func (x *GetRequestReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type AssetRequestList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*AssetRequest        `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetRequestList) Reset() {
	*x = AssetRequestList{}
	mi := &file_proto_asset_asset_request_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetRequestList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetRequestList) ProtoMessage() {}

func (x *AssetRequestList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_request_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetRequestList.ProtoReflect.Descriptor instead.
func (*AssetRequestList) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_request_proto_rawDescGZIP(), []int{8}
}

func (x *AssetRequestList) GetRequests() []*AssetRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *AssetRequestList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_asset_asset_request_proto protoreflect.FileDescriptor

const file_proto_asset_asset_request_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/asset/asset_request.proto\x12\x05asset\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17proto/asset/asset.proto\"\xae\x04\n" +
	"\fAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atype_id\x18\x02 \x01(\tR\x06typeId\x12\x1b\n" +
	"\ttype_name\x18\x03 \x01(\tR\btypeName\x12!\n" +
	"\fworkspace_id\x18\x04 \x01(\tR\vworkspaceId\x12!\n" +
	"\frequester_id\x18\x05 \x01(\tR\vrequesterId\x12%\n" +
	"\x0erequester_name\x18\x06 \x01(\tR\rrequesterName\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12$\n" +
	"\rjustification\x18\b \x01(\tR\rjustification\x12\x1a\n" +
	"\bquantity\x18\t \x01(\x05R\bquantity\x12*\n" +
	"\x11assigned_asset_id\x18\n" +
	" \x01(\tR\x0fassignedAssetId\x12\x1f\n" +
	"\vapprover_id\x18\v \x01(\tR\n" +
	"approverId\x12#\n" +
	"\rapprover_name\x18\f \x01(\tR\fapproverName\x12)\n" +
	"\x10approver_comment\x18\r \x01(\tR\x0fapproverComment\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd9\x01\n" +
	"\x15CreateAssetRequestReq\x12\x17\n" +
	"\atype_id\x18\x01 \x01(\tR\x06typeId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12)\n" +
	"\x11user_ngac_node_id\x18\x04 \x01(\tR\x0euserNgacNodeId\x12$\n" +
	"\rjustification\x18\x05 \x01(\tR\rjustification\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\"\x90\x01\n" +
	"\x11ApproveRequestReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12)\n" +
	"\x11user_ngac_node_id\x18\x03 \x01(\tR\x0euserNgacNodeId\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"\x8d\x01\n" +
	"\x10RejectRequestReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12)\n" +
	"\x11user_ngac_node_id\x18\x03 \x01(\tR\x0euserNgacNodeId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x8e\x01\n" +
	"\x0eAssignAssetReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12)\n" +
	"\x11user_ngac_node_id\x18\x04 \x01(\tR\x0euserNgacNodeId\"o\n" +
	"\x0eReturnAssetReq\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12)\n" +
	"\x11user_ngac_node_id\x18\x03 \x01(\tR\x0euserNgacNodeId\"\xdb\x01\n" +
	"\x0fListRequestsReq\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12)\n" +
	"\x11user_ngac_node_id\x18\x03 \x01(\tR\x0euserNgacNodeId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1b\n" +
	"\tmine_only\x18\x05 \x01(\bR\bmineOnly\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\a \x01(\x05R\x06offset\".\n" +
	"\rGetRequestReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"Y\n" +
	"\x10AssetRequestList\x12/\n" +
	"\brequests\x18\x01 \x03(\v2\x13.asset.AssetRequestR\brequests\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xc2\x03\n" +
	"\x13AssetRequestService\x12B\n" +
	"\rCreateRequest\x12\x1c.asset.CreateAssetRequestReq\x1a\x13.asset.AssetRequest\x12?\n" +
	"\x0eApproveRequest\x12\x18.asset.ApproveRequestReq\x1a\x13.asset.AssetRequest\x12=\n" +
	"\rRejectRequest\x12\x17.asset.RejectRequestReq\x1a\x13.asset.AssetRequest\x129\n" +
	"\vAssignAsset\x12\x15.asset.AssignAssetReq\x1a\x13.asset.AssetRequest\x122\n" +
	"\vReturnAsset\x12\x15.asset.ReturnAssetReq\x1a\f.asset.Empty\x12?\n" +
	"\fListRequests\x12\x16.asset.ListRequestsReq\x1a\x17.asset.AssetRequestList\x127\n" +
	"\n" +
	"GetRequest\x12\x14.asset.GetRequestReq\x1a\x13.asset.AssetRequestB\x1bZ\x19ngac-platform/proto/assetb\x06proto3"

var (
	file_proto_asset_asset_request_proto_rawDescOnce sync.Once
	file_proto_asset_asset_request_proto_rawDescData []byte
)

func file_proto_asset_asset_request_proto_rawDescGZIP() []byte {
	file_proto_asset_asset_request_proto_rawDescOnce.Do(func() {
		file_proto_asset_asset_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_asset_asset_request_proto_rawDesc), len(file_proto_asset_asset_request_proto_rawDesc)))
	})
	return file_proto_asset_asset_request_proto_rawDescData
}

var file_proto_asset_asset_request_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_asset_asset_request_proto_goTypes = []any{
	(*AssetRequest)(nil),          // 0: asset.AssetRequest
	(*CreateAssetRequestReq)(nil), // 1: asset.CreateAssetRequestReq
	(*ApproveRequestReq)(nil),     // 2: asset.ApproveRequestReq
	(*RejectRequestReq)(nil),      // 3: asset.RejectRequestReq
	(*AssignAssetReq)(nil),        // 4: asset.AssignAssetReq
	(*ReturnAssetReq)(nil),        // 5: asset.ReturnAssetReq
	(*ListRequestsReq)(nil),       // 6: asset.ListRequestsReq
	(*GetRequestReq)(nil),         // 7: asset.GetRequestReq
	(*AssetRequestList)(nil),      // 8: asset.AssetRequestList
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*Empty)(nil),                 // 10: asset.Empty
}
var file_proto_asset_asset_request_proto_depIdxs = []int32{
	9,  // 0: asset.AssetRequest.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: asset.AssetRequest.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: asset.AssetRequestList.requests:type_name -> asset.AssetRequest
	1,  // 3: asset.AssetRequestService.CreateRequest:input_type -> asset.CreateAssetRequestReq
	2,  // 4: asset.AssetRequestService.ApproveRequest:input_type -> asset.ApproveRequestReq
	3,  // 5: asset.AssetRequestService.RejectRequest:input_type -> asset.RejectRequestReq
	4,  // 6: asset.AssetRequestService.AssignAsset:input_type -> asset.AssignAssetReq
	5,  // 7: asset.AssetRequestService.ReturnAsset:input_type -> asset.ReturnAssetReq
	6,  // 8: asset.AssetRequestService.ListRequests:input_type -> asset.ListRequestsReq
	7,  // 9: asset.AssetRequestService.GetRequest:input_type -> asset.GetRequestReq
	0,  // 10: asset.AssetRequestService.CreateRequest:output_type -> asset.AssetRequest
	0,  // 11: asset.AssetRequestService.ApproveRequest:output_type -> asset.AssetRequest
	0,  // 12: asset.AssetRequestService.RejectRequest:output_type -> asset.AssetRequest
	0,  // 13: asset.AssetRequestService.AssignAsset:output_type -> asset.AssetRequest
	10, // 14: asset.AssetRequestService.ReturnAsset:output_type -> asset.Empty
	8,  // 15: asset.AssetRequestService.ListRequests:output_type -> asset.AssetRequestList
	0,  // 16: asset.AssetRequestService.GetRequest:output_type -> asset.AssetRequest
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_asset_asset_request_proto_init() }
func file_proto_asset_asset_request_proto_init() {
	if File_proto_asset_asset_request_proto != nil {
		return
	}
	file_proto_asset_asset_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_asset_asset_request_proto_rawDesc), len(file_proto_asset_asset_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_asset_asset_request_proto_goTypes,
		DependencyIndexes: file_proto_asset_asset_request_proto_depIdxs,
		MessageInfos:      file_proto_asset_asset_request_proto_msgTypes,
	}.Build()
	File_proto_asset_asset_request_proto = out.File
	file_proto_asset_asset_request_proto_goTypes = nil
	file_proto_asset_asset_request_proto_depIdxs = nil
}
