#!/usr/bin/env bash
# Deploys one release of the Nexus stack. Lives in /opt/nexus/releases/<tag>/ next to that release's
# docker-compose.yml, so running it from a release directory uses THAT release's compose file,
# nginx config and migrations. Shared state stays in /opt/nexus: .env, backups/, .deployed-tag.
#
#   cd /opt/nexus/releases/<tag> && NEXUS_OWNER=<owner> ./deploy.sh <tag>
#   ... ROLLBACK=1 ./deploy.sh <tag>    never migrates; tolerates a failed pull (images may be local)
#   ... SKIP_PULL=1 ./deploy.sh <tag>   do not pull; the images are already on this host
#
# Registry login: pass a short-lived token on stdin, e.g.
#   printf '%s' "$GITHUB_TOKEN" | GHCR_USER=<user> ./deploy.sh <tag>
# The login lives in a private, throw-away DOCKER_CONFIG that is deleted on exit, so the token never
# reaches root's own docker config and other apps' registry logins are neither read nor removed.
#
# Order: pull -> migrate (ledger, backup first; skipped on rollback) -> up --wait -> record
# /opt/nexus/.deployed-tag. The tag file is written only after every container is healthy, so it
# always names the last tag that came up; deploy.yml rolls back to it when the public check fails.
set -euo pipefail

RELEASE_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
APP_DIR=${APP_DIR:-$(cd "$RELEASE_DIR/../.." && pwd)}
TAG=${1:-}
OWNER=${NEXUS_OWNER:-}
GHCR_USER=${GHCR_USER:-github-actions}
WAIT_TIMEOUT=${WAIT_TIMEOUT:-300}
KEEP_RELEASES=${KEEP_RELEASES:-5}

log() { printf '[deploy] %s\n' "$*"; }
die() { printf '[deploy] ERROR: %s\n' "$*" >&2; exit 1; }

[[ $TAG =~ ^[A-Za-z0-9._-]{1,128}$ ]] || die "usage: [NEXUS_OWNER=<owner>] ./deploy.sh <tag>  (tag: letters, digits, . _ -)"
[[ $OWNER =~ ^[a-z0-9][a-z0-9-]*$ ]] || die "NEXUS_OWNER must be the lowercase GitHub owner (got '${OWNER}')"
[[ $GHCR_USER =~ ^[A-Za-z0-9][A-Za-z0-9-]*(\[bot\])?$ ]] || die "invalid GHCR_USER"

[[ -f $APP_DIR/.env ]] || die "$APP_DIR/.env missing; run server-bootstrap.sh first"
[[ -f $RELEASE_DIR/docker-compose.yml ]] || die "$RELEASE_DIR/docker-compose.yml missing"
[[ $(basename "$RELEASE_DIR") == "$TAG" ]] || die "run this from $APP_DIR/releases/$TAG (found $RELEASE_DIR)"
cd "$RELEASE_DIR"

# One deploy at a time, whether it comes from CI or from a shell on this host.
exec 9>"$APP_DIR/.deploy.lock"
flock -n 9 || die "another deploy is running"

export NEXUS_OWNER="$OWNER" NEXUS_TAG="$TAG" NEXUS_HOME="$APP_DIR" COMPOSE_ENV_FILES="$APP_DIR/.env"
ROLLBACK=${ROLLBACK:-0}

# Private docker config for the registry login. Compose and buildx are CLI plugins looked up in
# the config dir, so link root's plugin dir (if it has one) into the private one.
DOCKER_CONFIG=$(mktemp -d)
export DOCKER_CONFIG
trap 'rm -rf "$DOCKER_CONFIG"' EXIT
if [[ -d ${HOME:-/root}/.docker/cli-plugins ]]; then
  ln -s "${HOME:-/root}/.docker/cli-plugins" "$DOCKER_CONFIG/cli-plugins"
fi

if [[ ! -t 0 ]]; then
  token=$(cat)
  if [[ -n $token ]]; then
    printf '%s' "$token" | docker login ghcr.io -u "$GHCR_USER" --password-stdin >/dev/null
    log "logged in to ghcr.io (private docker config)"
  fi
  unset token
fi

previous=""
[[ -f $APP_DIR/.deployed-tag ]] && previous=$(<"$APP_DIR/.deployed-tag")
log "deploying tag $TAG (currently: ${previous:-none})$([[ $ROLLBACK == 1 ]] && echo " [rollback]")"

# nginx trusts X-Forwarded-For only from the shared `traefik` network. Its subnet is not ours, so
# read it from Docker and hand it to nginx as an include.
mkdir -p nginx
subnets=$(docker network inspect traefik --format '{{range .IPAM.Config}}{{.Subnet}}{{"\n"}}{{end}}') ||
  die "docker network 'traefik' not found"
[[ -n $subnets ]] || die "docker network 'traefik' has no subnet"
{
  echo "# Generated by deploy.sh from 'docker network inspect traefik'. Do not edit."
  while read -r cidr; do
    [[ $cidr =~ ^[0-9a-fA-F:.]+/[0-9]+$ ]] || die "unexpected subnet '$cidr'"
    echo "set_real_ip_from $cidr;"
  done <<<"$subnets"
} >nginx/real-ip.conf

if [[ ${SKIP_PULL:-0} == 1 ]]; then
  log "SKIP_PULL=1: using images already on this host"
elif ! docker compose pull --quiet; then
  [[ $ROLLBACK == 1 ]] || die "image pull failed"
  log "pull failed during rollback; continuing with local images"
fi

marker="$APP_DIR/backups/.migrations-applied"
rm -f "$marker"
if [[ $ROLLBACK == 1 ]]; then
  log "rollback: skipping migrations (schema changes are forward-only)"
else
  log "migrating (backup first)"
  docker compose --profile tools run --rm migrate
fi

log "starting stack"
docker compose up -d --remove-orphans --wait --wait-timeout "$WAIT_TIMEOUT"

# The policy services keep the authorization graph in memory and read the database only at
# start. A migration can rewrite graph rows, so restart them whenever one was applied.
if [[ -e $marker ]]; then
  log "migrations were applied: restarting policy services to reload the graph"
  docker compose up -d --force-recreate --no-deps --wait --wait-timeout "$WAIT_TIMEOUT" policy policy-read
  rm -f "$marker"
fi

printf '%s\n' "$TAG" >"$APP_DIR/.deployed-tag"
log "tag $TAG is up"

# Drop this stack's images from older tags; keep the new and the previous one for rollback.
# Scoped to this repository's images, never docker-wide prune on a shared host.
docker image ls --format '{{.Repository}}:{{.Tag}}' |
  grep -E "^ghcr\.io/${OWNER}/nexus-[a-z-]+:" |
  grep -vE ":(${TAG}|${previous:-__none__})$" |
  xargs -r docker image rm >/dev/null 2>&1 || true

# Keep the newest releases, always including this one and the previous one.
if [[ -d $APP_DIR/releases ]]; then
  # shellcheck disable=SC2012  # directory names are validated tags
  ls -1t "$APP_DIR/releases" | tail -n +"$((KEEP_RELEASES + 1))" | while read -r old; do
    [[ $old == "$TAG" || $old == "$previous" ]] && continue
    [[ $old =~ ^[A-Za-z0-9._-]+$ ]] && rm -rf "${APP_DIR:?}/releases/$old"
  done
fi
log "done"
