// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/policy/policy_read.proto

package policy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyReadService_CheckAccess_FullMethodName    = "/policy.PolicyReadService/CheckAccess"
	PolicyReadService_GetNode_FullMethodName        = "/policy.PolicyReadService/GetNode"
	PolicyReadService_FindNodeByName_FullMethodName = "/policy.PolicyReadService/FindNodeByName"
	PolicyReadService_GetNodesByType_FullMethodName = "/policy.PolicyReadService/GetNodesByType"
	PolicyReadService_IsAssigned_FullMethodName     = "/policy.PolicyReadService/IsAssigned"
	PolicyReadService_GetAncestors_FullMethodName   = "/policy.PolicyReadService/GetAncestors"
	PolicyReadService_GetDescendants_FullMethodName = "/policy.PolicyReadService/GetDescendants"
	PolicyReadService_GetChildren_FullMethodName    = "/policy.PolicyReadService/GetChildren"
	PolicyReadService_GetParents_FullMethodName     = "/policy.PolicyReadService/GetParents"
)

// PolicyReadServiceClient is the client API for PolicyReadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PolicyReadService handles read-only operations against the NGAC graph.
// Designed to run as stateless replicas behind a load balancer.
type PolicyReadServiceClient interface {
	// Access checks
	CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*AccessDecision, error)
	// Node queries (read-only)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*NGACNode, error)
	FindNodeByName(ctx context.Context, in *FindNodeByNameRequest, opts ...grpc.CallOption) (*NGACNode, error)
	GetNodesByType(ctx context.Context, in *GetNodesByTypeRequest, opts ...grpc.CallOption) (*NodeList, error)
	IsAssigned(ctx context.Context, in *IsAssignedRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	// Graph traversal (read-only)
	GetAncestors(ctx context.Context, in *GetAncestorsRequest, opts ...grpc.CallOption) (*NodeList, error)
	GetDescendants(ctx context.Context, in *GetDescendantsRequest, opts ...grpc.CallOption) (*NodeList, error)
	GetChildren(ctx context.Context, in *GetChildrenRequest, opts ...grpc.CallOption) (*NodeList, error)
	GetParents(ctx context.Context, in *GetParentsRequest, opts ...grpc.CallOption) (*NodeList, error)
}

type policyReadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyReadServiceClient(cc grpc.ClientConnInterface) PolicyReadServiceClient {
	return &policyReadServiceClient{cc}
}

func (c *policyReadServiceClient) CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*AccessDecision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessDecision)
	err := c.cc.Invoke(ctx, PolicyReadService_CheckAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyReadServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*NGACNode, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NGACNode)
	err := c.cc.Invoke(ctx, PolicyReadService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyReadServiceClient) FindNodeByName(ctx context.Context, in *FindNodeByNameRequest, opts ...grpc.CallOption) (*NGACNode, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NGACNode)
	err := c.cc.Invoke(ctx, PolicyReadService_FindNodeByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyReadServiceClient) GetNodesByType(ctx context.Context, in *GetNodesByTypeRequest, opts ...grpc.CallOption) (*NodeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeList)
	err := c.cc.Invoke(ctx, PolicyReadService_GetNodesByType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyReadServiceClient) IsAssigned(ctx context.Context, in *IsAssignedRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, PolicyReadService_IsAssigned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyReadServiceClient) GetAncestors(ctx context.Context, in *GetAncestorsRequest, opts ...grpc.CallOption) (*NodeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeList)
	err := c.cc.Invoke(ctx, PolicyReadService_GetAncestors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyReadServiceClient) GetDescendants(ctx context.Context, in *GetDescendantsRequest, opts ...grpc.CallOption) (*NodeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeList)
	err := c.cc.Invoke(ctx, PolicyReadService_GetDescendants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyReadServiceClient) GetChildren(ctx context.Context, in *GetChildrenRequest, opts ...grpc.CallOption) (*NodeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeList)
	err := c.cc.Invoke(ctx, PolicyReadService_GetChildren_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyReadServiceClient) GetParents(ctx context.Context, in *GetParentsRequest, opts ...grpc.CallOption) (*NodeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeList)
	err := c.cc.Invoke(ctx, PolicyReadService_GetParents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyReadServiceServer is the server API for PolicyReadService service.
// All implementations must embed UnimplementedPolicyReadServiceServer
// for forward compatibility.
//
// PolicyReadService handles read-only operations against the NGAC graph.
// Designed to run as stateless replicas behind a load balancer.
type PolicyReadServiceServer interface {
	// Access checks
	CheckAccess(context.Context, *CheckAccessRequest) (*AccessDecision, error)
	// Node queries (read-only)
	GetNode(context.Context, *GetNodeRequest) (*NGACNode, error)
	FindNodeByName(context.Context, *FindNodeByNameRequest) (*NGACNode, error)
	GetNodesByType(context.Context, *GetNodesByTypeRequest) (*NodeList, error)
	IsAssigned(context.Context, *IsAssignedRequest) (*BoolResponse, error)
	// Graph traversal (read-only)
	GetAncestors(context.Context, *GetAncestorsRequest) (*NodeList, error)
	GetDescendants(context.Context, *GetDescendantsRequest) (*NodeList, error)
	GetChildren(context.Context, *GetChildrenRequest) (*NodeList, error)
	GetParents(context.Context, *GetParentsRequest) (*NodeList, error)
	mustEmbedUnimplementedPolicyReadServiceServer()
}

// UnimplementedPolicyReadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyReadServiceServer struct{}

func (UnimplementedPolicyReadServiceServer) CheckAccess(context.Context, *CheckAccessRequest) (*AccessDecision, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAccess not implemented")
}
func (UnimplementedPolicyReadServiceServer) GetNode(context.Context, *GetNodeRequest) (*NGACNode, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedPolicyReadServiceServer) FindNodeByName(context.Context, *FindNodeByNameRequest) (*NGACNode, error) {
	return nil, status.Error(codes.Unimplemented, "method FindNodeByName not implemented")
}
func (UnimplementedPolicyReadServiceServer) GetNodesByType(context.Context, *GetNodesByTypeRequest) (*NodeList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodesByType not implemented")
}
func (UnimplementedPolicyReadServiceServer) IsAssigned(context.Context, *IsAssignedRequest) (*BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsAssigned not implemented")
}
func (UnimplementedPolicyReadServiceServer) GetAncestors(context.Context, *GetAncestorsRequest) (*NodeList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAncestors not implemented")
}
func (UnimplementedPolicyReadServiceServer) GetDescendants(context.Context, *GetDescendantsRequest) (*NodeList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDescendants not implemented")
}
func (UnimplementedPolicyReadServiceServer) GetChildren(context.Context, *GetChildrenRequest) (*NodeList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChildren not implemented")
}
func (UnimplementedPolicyReadServiceServer) GetParents(context.Context, *GetParentsRequest) (*NodeList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParents not implemented")
}
func (UnimplementedPolicyReadServiceServer) mustEmbedUnimplementedPolicyReadServiceServer() {}
func (UnimplementedPolicyReadServiceServer) testEmbeddedByValue()                           {}

// UnsafePolicyReadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyReadServiceServer will
// result in compilation errors.
type UnsafePolicyReadServiceServer interface {
	mustEmbedUnimplementedPolicyReadServiceServer()
}

func RegisterPolicyReadServiceServer(s grpc.ServiceRegistrar, srv PolicyReadServiceServer) {
	// If the following call panics, it indicates UnimplementedPolicyReadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyReadService_ServiceDesc, srv)
}

func _PolicyReadService_CheckAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyReadServiceServer).CheckAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyReadService_CheckAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyReadServiceServer).CheckAccess(ctx, req.(*CheckAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyReadService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyReadServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyReadService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyReadServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyReadService_FindNodeByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindNodeByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyReadServiceServer).FindNodeByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyReadService_FindNodeByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyReadServiceServer).FindNodeByName(ctx, req.(*FindNodeByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyReadService_GetNodesByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesByTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyReadServiceServer).GetNodesByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyReadService_GetNodesByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyReadServiceServer).GetNodesByType(ctx, req.(*GetNodesByTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyReadService_IsAssigned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAssignedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyReadServiceServer).IsAssigned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyReadService_IsAssigned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyReadServiceServer).IsAssigned(ctx, req.(*IsAssignedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyReadService_GetAncestors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAncestorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyReadServiceServer).GetAncestors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyReadService_GetAncestors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyReadServiceServer).GetAncestors(ctx, req.(*GetAncestorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyReadService_GetDescendants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDescendantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyReadServiceServer).GetDescendants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyReadService_GetDescendants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyReadServiceServer).GetDescendants(ctx, req.(*GetDescendantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyReadService_GetChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChildrenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyReadServiceServer).GetChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyReadService_GetChildren_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyReadServiceServer).GetChildren(ctx, req.(*GetChildrenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyReadService_GetParents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyReadServiceServer).GetParents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyReadService_GetParents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyReadServiceServer).GetParents(ctx, req.(*GetParentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyReadService_ServiceDesc is the grpc.ServiceDesc for PolicyReadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyReadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "policy.PolicyReadService",
	HandlerType: (*PolicyReadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAccess",
			Handler:    _PolicyReadService_CheckAccess_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _PolicyReadService_GetNode_Handler,
		},
		{
			MethodName: "FindNodeByName",
			Handler:    _PolicyReadService_FindNodeByName_Handler,
		},
		{
			MethodName: "GetNodesByType",
			Handler:    _PolicyReadService_GetNodesByType_Handler,
		},
		{
			MethodName: "IsAssigned",
			Handler:    _PolicyReadService_IsAssigned_Handler,
		},
		{
			MethodName: "GetAncestors",
			Handler:    _PolicyReadService_GetAncestors_Handler,
		},
		{
			MethodName: "GetDescendants",
			Handler:    _PolicyReadService_GetDescendants_Handler,
		},
		{
			MethodName: "GetChildren",
			Handler:    _PolicyReadService_GetChildren_Handler,
		},
		{
			MethodName: "GetParents",
			Handler:    _PolicyReadService_GetParents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/policy/policy_read.proto",
}
