// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/policy/policy.proto

package policy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_policy_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{0}
}

type BoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolResponse) Reset() {
	*x = BoolResponse{}
	mi := &file_proto_policy_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolResponse) ProtoMessage() {}

func (x *BoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolResponse.ProtoReflect.Descriptor instead.
func (*BoolResponse) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{1}
}

func (x *BoolResponse) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type NGACNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NodeType      string                 `protobuf:"bytes,3,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NGACNode) Reset() {
	*x = NGACNode{}
	mi := &file_proto_policy_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NGACNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NGACNode) ProtoMessage() {}

func (x *NGACNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NGACNode.ProtoReflect.Descriptor instead.
func (*NGACNode) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{2}
}

func (x *NGACNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NGACNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NGACNode) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *NGACNode) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *NGACNode) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Assignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChildId       string                 `protobuf:"bytes,2,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_proto_policy_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{3}
}

func (x *Assignment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Assignment) GetChildId() string {
	if x != nil {
		return x.ChildId
	}
	return ""
}

func (x *Assignment) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type Association struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UaId          string                 `protobuf:"bytes,2,opt,name=ua_id,json=uaId,proto3" json:"ua_id,omitempty"`
	OaId          string                 `protobuf:"bytes,3,opt,name=oa_id,json=oaId,proto3" json:"oa_id,omitempty"`
	Operations    []string               `protobuf:"bytes,4,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Association) Reset() {
	*x = Association{}
	mi := &file_proto_policy_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Association) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Association) ProtoMessage() {}

func (x *Association) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Association.ProtoReflect.Descriptor instead.
func (*Association) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{4}
}

func (x *Association) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Association) GetUaId() string {
	if x != nil {
		return x.UaId
	}
	return ""
}

func (x *Association) GetOaId() string {
	if x != nil {
		return x.OaId
	}
	return ""
}

func (x *Association) GetOperations() []string {
	if x != nil {
		return x.Operations
	}
	return nil
}

type CheckAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserNodeId    string                 `protobuf:"bytes,1,opt,name=user_node_id,json=userNodeId,proto3" json:"user_node_id,omitempty"`
	ObjectNodeId  string                 `protobuf:"bytes,2,opt,name=object_node_id,json=objectNodeId,proto3" json:"object_node_id,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	WorkspaceId   *string                `protobuf:"bytes,4,opt,name=workspace_id,json=workspaceId,proto3,oneof" json:"workspace_id,omitempty"` // Optional: enables shard-based evaluation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessRequest) Reset() {
	*x = CheckAccessRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessRequest) ProtoMessage() {}

func (x *CheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{5}
}

func (x *CheckAccessRequest) GetUserNodeId() string {
	if x != nil {
		return x.UserNodeId
	}
	return ""
}

func (x *CheckAccessRequest) GetObjectNodeId() string {
	if x != nil {
		return x.ObjectNodeId
	}
	return ""
}

func (x *CheckAccessRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *CheckAccessRequest) GetWorkspaceId() string {
	if x != nil && x.WorkspaceId != nil {
		return *x.WorkspaceId
	}
	return ""
}

type AccessDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      string                 `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Object        string                 `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	Operation     string                 `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	Explanation   *AccessExplanation     `protobuf:"bytes,5,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessDecision) Reset() {
	*x = AccessDecision{}
	mi := &file_proto_policy_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessDecision) ProtoMessage() {}

func (x *AccessDecision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessDecision.ProtoReflect.Descriptor instead.
func (*AccessDecision) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{6}
}

func (x *AccessDecision) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *AccessDecision) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AccessDecision) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *AccessDecision) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *AccessDecision) GetExplanation() *AccessExplanation {
	if x != nil {
		return x.Explanation
	}
	return nil
}

type AccessExplanation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  []string               `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	// Deprecated: Marked as deprecated in proto/policy/policy.proto.
	PolicyClass        string             `protobuf:"bytes,2,opt,name=policy_class,json=policyClass,proto3" json:"policy_class,omitempty"` // Use policy_classes instead
	UserAttributes     []string           `protobuf:"bytes,3,rep,name=user_attributes,json=userAttributes,proto3" json:"user_attributes,omitempty"`
	ObjectAttributes   []string           `protobuf:"bytes,4,rep,name=object_attributes,json=objectAttributes,proto3" json:"object_attributes,omitempty"`
	Reason             string             `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	ConstraintsChecked []string           `protobuf:"bytes,6,rep,name=constraints_checked,json=constraintsChecked,proto3" json:"constraints_checked,omitempty"`
	ConstraintDenied   *ConstraintDenial  `protobuf:"bytes,7,opt,name=constraint_denied,json=constraintDenied,proto3" json:"constraint_denied,omitempty"`
	ProhibitionDenied  *ProhibitionDenial `protobuf:"bytes,8,opt,name=prohibition_denied,json=prohibitionDenied,proto3" json:"prohibition_denied,omitempty"`
	PolicyClasses      []string           `protobuf:"bytes,9,rep,name=policy_classes,json=policyClasses,proto3" json:"policy_classes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AccessExplanation) Reset() {
	*x = AccessExplanation{}
	mi := &file_proto_policy_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessExplanation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessExplanation) ProtoMessage() {}

func (x *AccessExplanation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessExplanation.ProtoReflect.Descriptor instead.
func (*AccessExplanation) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{7}
}

func (x *AccessExplanation) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

// Deprecated: Marked as deprecated in proto/policy/policy.proto.
func (x *AccessExplanation) GetPolicyClass() string {
	if x != nil {
		return x.PolicyClass
	}
	return ""
}

func (x *AccessExplanation) GetUserAttributes() []string {
	if x != nil {
		return x.UserAttributes
	}
	return nil
}

func (x *AccessExplanation) GetObjectAttributes() []string {
	if x != nil {
		return x.ObjectAttributes
	}
	return nil
}

func (x *AccessExplanation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AccessExplanation) GetConstraintsChecked() []string {
	if x != nil {
		return x.ConstraintsChecked
	}
	return nil
}

func (x *AccessExplanation) GetConstraintDenied() *ConstraintDenial {
	if x != nil {
		return x.ConstraintDenied
	}
	return nil
}

func (x *AccessExplanation) GetProhibitionDenied() *ProhibitionDenial {
	if x != nil {
		return x.ProhibitionDenied
	}
	return nil
}

func (x *AccessExplanation) GetPolicyClasses() []string {
	if x != nil {
		return x.PolicyClasses
	}
	return nil
}

type ConstraintDenial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConstraintDenial) Reset() {
	*x = ConstraintDenial{}
	mi := &file_proto_policy_policy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConstraintDenial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstraintDenial) ProtoMessage() {}

func (x *ConstraintDenial) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstraintDenial.ProtoReflect.Descriptor instead.
func (*ConstraintDenial) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{8}
}

func (x *ConstraintDenial) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConstraintDenial) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NodeType      string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{9}
}

func (x *CreateNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNodeRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *CreateNodeRequest) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type DeleteNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeRequest) Reset() {
	*x = DeleteNodeRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeRequest) ProtoMessage() {}

func (x *DeleteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{11}
}

func (x *GetNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type FindNodeByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NodeType      string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNodeByNameRequest) Reset() {
	*x = FindNodeByNameRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNodeByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNodeByNameRequest) ProtoMessage() {}

func (x *FindNodeByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNodeByNameRequest.ProtoReflect.Descriptor instead.
func (*FindNodeByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{12}
}

func (x *FindNodeByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FindNodeByNameRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

type GetNodesByTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      string                 `protobuf:"bytes,1,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesByTypeRequest) Reset() {
	*x = GetNodesByTypeRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesByTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesByTypeRequest) ProtoMessage() {}

func (x *GetNodesByTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesByTypeRequest.ProtoReflect.Descriptor instead.
func (*GetNodesByTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{13}
}

func (x *GetNodesByTypeRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

type NodeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NGACNode            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeList) Reset() {
	*x = NodeList{}
	mi := &file_proto_policy_policy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeList) ProtoMessage() {}

func (x *NodeList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeList.ProtoReflect.Descriptor instead.
func (*NodeList) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{14}
}

func (x *NodeList) GetNodes() []*NGACNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type CreateAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChildId       string                 `protobuf:"bytes,1,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssignmentRequest) Reset() {
	*x = CreateAssignmentRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssignmentRequest) ProtoMessage() {}

func (x *CreateAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssignmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{15}
}

func (x *CreateAssignmentRequest) GetChildId() string {
	if x != nil {
		return x.ChildId
	}
	return ""
}

func (x *CreateAssignmentRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type RemoveAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChildId       string                 `protobuf:"bytes,1,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAssignmentRequest) Reset() {
	*x = RemoveAssignmentRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAssignmentRequest) ProtoMessage() {}

func (x *RemoveAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAssignmentRequest.ProtoReflect.Descriptor instead.
func (*RemoveAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveAssignmentRequest) GetChildId() string {
	if x != nil {
		return x.ChildId
	}
	return ""
}

func (x *RemoveAssignmentRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type IsAssignedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChildId       string                 `protobuf:"bytes,1,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAssignedRequest) Reset() {
	*x = IsAssignedRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAssignedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAssignedRequest) ProtoMessage() {}

func (x *IsAssignedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAssignedRequest.ProtoReflect.Descriptor instead.
func (*IsAssignedRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{17}
}

func (x *IsAssignedRequest) GetChildId() string {
	if x != nil {
		return x.ChildId
	}
	return ""
}

func (x *IsAssignedRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type CreateAssociationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UaId          string                 `protobuf:"bytes,1,opt,name=ua_id,json=uaId,proto3" json:"ua_id,omitempty"`
	OaId          string                 `protobuf:"bytes,2,opt,name=oa_id,json=oaId,proto3" json:"oa_id,omitempty"`
	Operations    []string               `protobuf:"bytes,3,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssociationRequest) Reset() {
	*x = CreateAssociationRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssociationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssociationRequest) ProtoMessage() {}

func (x *CreateAssociationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssociationRequest.ProtoReflect.Descriptor instead.
func (*CreateAssociationRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{18}
}

func (x *CreateAssociationRequest) GetUaId() string {
	if x != nil {
		return x.UaId
	}
	return ""
}

func (x *CreateAssociationRequest) GetOaId() string {
	if x != nil {
		return x.OaId
	}
	return ""
}

func (x *CreateAssociationRequest) GetOperations() []string {
	if x != nil {
		return x.Operations
	}
	return nil
}

type RemoveAssociationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UaId          string                 `protobuf:"bytes,1,opt,name=ua_id,json=uaId,proto3" json:"ua_id,omitempty"`
	OaId          string                 `protobuf:"bytes,2,opt,name=oa_id,json=oaId,proto3" json:"oa_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAssociationRequest) Reset() {
	*x = RemoveAssociationRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAssociationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAssociationRequest) ProtoMessage() {}

func (x *RemoveAssociationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAssociationRequest.ProtoReflect.Descriptor instead.
func (*RemoveAssociationRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveAssociationRequest) GetUaId() string {
	if x != nil {
		return x.UaId
	}
	return ""
}

func (x *RemoveAssociationRequest) GetOaId() string {
	if x != nil {
		return x.OaId
	}
	return ""
}

type GetAncestorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAncestorsRequest) Reset() {
	*x = GetAncestorsRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAncestorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAncestorsRequest) ProtoMessage() {}

func (x *GetAncestorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAncestorsRequest.ProtoReflect.Descriptor instead.
func (*GetAncestorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{20}
}

func (x *GetAncestorsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetDescendantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDescendantsRequest) Reset() {
	*x = GetDescendantsRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDescendantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDescendantsRequest) ProtoMessage() {}

func (x *GetDescendantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDescendantsRequest.ProtoReflect.Descriptor instead.
func (*GetDescendantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{21}
}

func (x *GetDescendantsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetChildrenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChildrenRequest) Reset() {
	*x = GetChildrenRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChildrenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChildrenRequest) ProtoMessage() {}

func (x *GetChildrenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChildrenRequest.ProtoReflect.Descriptor instead.
func (*GetChildrenRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{22}
}

func (x *GetChildrenRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetParentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParentsRequest) Reset() {
	*x = GetParentsRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParentsRequest) ProtoMessage() {}

func (x *GetParentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParentsRequest.ProtoReflect.Descriptor instead.
func (*GetParentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{23}
}

func (x *GetParentsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// BatchCheckAccess — resolve permissions for multiple objects in one call.
type BatchCheckAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserNodeId    string                 `protobuf:"bytes,1,opt,name=user_node_id,json=userNodeId,proto3" json:"user_node_id,omitempty"`
	ObjectIds     []string               `protobuf:"bytes,2,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	Operations    []string               `protobuf:"bytes,3,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckAccessRequest) Reset() {
	*x = BatchCheckAccessRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckAccessRequest) ProtoMessage() {}

func (x *BatchCheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckAccessRequest.ProtoReflect.Descriptor instead.
func (*BatchCheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{24}
}

func (x *BatchCheckAccessRequest) GetUserNodeId() string {
	if x != nil {
		return x.UserNodeId
	}
	return ""
}

func (x *BatchCheckAccessRequest) GetObjectIds() []string {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

func (x *BatchCheckAccessRequest) GetOperations() []string {
	if x != nil {
		return x.Operations
	}
	return nil
}

type BatchAccessResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key = object_id, value = permissions for that object
	Results       map[string]*ObjectPermissions `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAccessResult) Reset() {
	*x = BatchAccessResult{}
	mi := &file_proto_policy_policy_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAccessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAccessResult) ProtoMessage() {}

func (x *BatchAccessResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAccessResult.ProtoReflect.Descriptor instead.
func (*BatchAccessResult) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{25}
}

func (x *BatchAccessResult) GetResults() map[string]*ObjectPermissions {
	if x != nil {
		return x.Results
	}
	return nil
}

type ObjectPermissions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key = operation name (e.g. "write"), value = allowed
	Permissions   map[string]bool `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectPermissions) Reset() {
	*x = ObjectPermissions{}
	mi := &file_proto_policy_policy_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectPermissions) ProtoMessage() {}

func (x *ObjectPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectPermissions.ProtoReflect.Descriptor instead.
func (*ObjectPermissions) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{26}
}

func (x *ObjectPermissions) GetPermissions() map[string]bool {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type Prohibition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SubjectId     string                 `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Operations    []string               `protobuf:"bytes,4,rep,name=operations,proto3" json:"operations,omitempty"`
	TargetOaIds   []string               `protobuf:"bytes,5,rep,name=target_oa_ids,json=targetOaIds,proto3" json:"target_oa_ids,omitempty"`
	Intersection  bool                   `protobuf:"varint,6,opt,name=intersection,proto3" json:"intersection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prohibition) Reset() {
	*x = Prohibition{}
	mi := &file_proto_policy_policy_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prohibition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prohibition) ProtoMessage() {}

func (x *Prohibition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prohibition.ProtoReflect.Descriptor instead.
func (*Prohibition) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{27}
}

func (x *Prohibition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Prohibition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Prohibition) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *Prohibition) GetOperations() []string {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *Prohibition) GetTargetOaIds() []string {
	if x != nil {
		return x.TargetOaIds
	}
	return nil
}

func (x *Prohibition) GetIntersection() bool {
	if x != nil {
		return x.Intersection
	}
	return false
}

type CreateProhibitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Operations    []string               `protobuf:"bytes,3,rep,name=operations,proto3" json:"operations,omitempty"`
	TargetOaIds   []string               `protobuf:"bytes,4,rep,name=target_oa_ids,json=targetOaIds,proto3" json:"target_oa_ids,omitempty"`
	Intersection  bool                   `protobuf:"varint,5,opt,name=intersection,proto3" json:"intersection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProhibitionRequest) Reset() {
	*x = CreateProhibitionRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProhibitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProhibitionRequest) ProtoMessage() {}

func (x *CreateProhibitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProhibitionRequest.ProtoReflect.Descriptor instead.
func (*CreateProhibitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{28}
}

func (x *CreateProhibitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProhibitionRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *CreateProhibitionRequest) GetOperations() []string {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *CreateProhibitionRequest) GetTargetOaIds() []string {
	if x != nil {
		return x.TargetOaIds
	}
	return nil
}

func (x *CreateProhibitionRequest) GetIntersection() bool {
	if x != nil {
		return x.Intersection
	}
	return false
}

type RemoveProhibitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProhibitionRequest) Reset() {
	*x = RemoveProhibitionRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProhibitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProhibitionRequest) ProtoMessage() {}

func (x *RemoveProhibitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProhibitionRequest.ProtoReflect.Descriptor instead.
func (*RemoveProhibitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{29}
}

func (x *RemoveProhibitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListProhibitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectId     string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProhibitionsRequest) Reset() {
	*x = ListProhibitionsRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProhibitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProhibitionsRequest) ProtoMessage() {}

func (x *ListProhibitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProhibitionsRequest.ProtoReflect.Descriptor instead.
func (*ListProhibitionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{30}
}

func (x *ListProhibitionsRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

type ProhibitionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prohibitions  []*Prohibition         `protobuf:"bytes,1,rep,name=prohibitions,proto3" json:"prohibitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProhibitionList) Reset() {
	*x = ProhibitionList{}
	mi := &file_proto_policy_policy_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProhibitionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProhibitionList) ProtoMessage() {}

func (x *ProhibitionList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProhibitionList.ProtoReflect.Descriptor instead.
func (*ProhibitionList) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{31}
}

func (x *ProhibitionList) GetProhibitions() []*Prohibition {
	if x != nil {
		return x.Prohibitions
	}
	return nil
}

type ProhibitionDenial struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProhibitionName string                 `protobuf:"bytes,1,opt,name=prohibition_name,json=prohibitionName,proto3" json:"prohibition_name,omitempty"`
	SubjectId       string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProhibitionDenial) Reset() {
	*x = ProhibitionDenial{}
	mi := &file_proto_policy_policy_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProhibitionDenial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProhibitionDenial) ProtoMessage() {}

func (x *ProhibitionDenial) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProhibitionDenial.ProtoReflect.Descriptor instead.
func (*ProhibitionDenial) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{32}
}

func (x *ProhibitionDenial) GetProhibitionName() string {
	if x != nil {
		return x.ProhibitionName
	}
	return ""
}

func (x *ProhibitionDenial) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

type RegisterOperationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []string               `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterOperationsRequest) Reset() {
	*x = RegisterOperationsRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOperationsRequest) ProtoMessage() {}

func (x *RegisterOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOperationsRequest.ProtoReflect.Descriptor instead.
func (*RegisterOperationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{33}
}

func (x *RegisterOperationsRequest) GetOperations() []string {
	if x != nil {
		return x.Operations
	}
	return nil
}

type RegisterOperationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registered    []string               `protobuf:"bytes,1,rep,name=registered,proto3" json:"registered,omitempty"`
	AlreadyExists []string               `protobuf:"bytes,2,rep,name=already_exists,json=alreadyExists,proto3" json:"already_exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterOperationsResponse) Reset() {
	*x = RegisterOperationsResponse{}
	mi := &file_proto_policy_policy_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOperationsResponse) ProtoMessage() {}

func (x *RegisterOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOperationsResponse.ProtoReflect.Descriptor instead.
func (*RegisterOperationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{34}
}

func (x *RegisterOperationsResponse) GetRegistered() []string {
	if x != nil {
		return x.Registered
	}
	return nil
}

func (x *RegisterOperationsResponse) GetAlreadyExists() []string {
	if x != nil {
		return x.AlreadyExists
	}
	return nil
}

type OperationList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []string               `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationList) Reset() {
	*x = OperationList{}
	mi := &file_proto_policy_policy_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationList) ProtoMessage() {}

func (x *OperationList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationList.ProtoReflect.Descriptor instead.
func (*OperationList) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{35}
}

func (x *OperationList) GetOperations() []string {
	if x != nil {
		return x.Operations
	}
	return nil
}

type InvalidateCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIds       []string               `protobuf:"bytes,1,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateCacheRequest) Reset() {
	*x = InvalidateCacheRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateCacheRequest) ProtoMessage() {}

func (x *InvalidateCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateCacheRequest.ProtoReflect.Descriptor instead.
func (*InvalidateCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{36}
}

func (x *InvalidateCacheRequest) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *InvalidateCacheRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type InvalidateCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	L1KeysDeleted int32                  `protobuf:"varint,1,opt,name=l1_keys_deleted,json=l1KeysDeleted,proto3" json:"l1_keys_deleted,omitempty"`
	L2RowsDeleted int32                  `protobuf:"varint,2,opt,name=l2_rows_deleted,json=l2RowsDeleted,proto3" json:"l2_rows_deleted,omitempty"`
	NewVersion    int64                  `protobuf:"varint,3,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateCacheResponse) Reset() {
	*x = InvalidateCacheResponse{}
	mi := &file_proto_policy_policy_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateCacheResponse) ProtoMessage() {}

func (x *InvalidateCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateCacheResponse.ProtoReflect.Descriptor instead.
func (*InvalidateCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{37}
}

func (x *InvalidateCacheResponse) GetL1KeysDeleted() int32 {
	if x != nil {
		return x.L1KeysDeleted
	}
	return 0
}

func (x *InvalidateCacheResponse) GetL2RowsDeleted() int32 {
	if x != nil {
		return x.L2RowsDeleted
	}
	return 0
}

func (x *InvalidateCacheResponse) GetNewVersion() int64 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

var File_proto_policy_policy_proto protoreflect.FileDescriptor

const file_proto_policy_policy_proto_rawDesc = "" +
	"\n" +
	"\x19proto/policy/policy.proto\x12\x06policy\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"$\n" +
	"\fBoolResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\"\x87\x02\n" +
	"\bNGACNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tnode_type\x18\x03 \x01(\tR\bnodeType\x12@\n" +
	"\n" +
	"properties\x18\x04 \x03(\v2 .policy.NGACNode.PropertiesEntryR\n" +
	"properties\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\n" +
	"Assignment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bchild_id\x18\x02 \x01(\tR\achildId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\"g\n" +
	"\vAssociation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x13\n" +
	"\x05ua_id\x18\x02 \x01(\tR\x04uaId\x12\x13\n" +
	"\x05oa_id\x18\x03 \x01(\tR\x04oaId\x12\x1e\n" +
	"\n" +
	"operations\x18\x04 \x03(\tR\n" +
	"operations\"\xb3\x01\n" +
	"\x12CheckAccessRequest\x12 \n" +
	"\fuser_node_id\x18\x01 \x01(\tR\n" +
	"userNodeId\x12$\n" +
	"\x0eobject_node_id\x18\x02 \x01(\tR\fobjectNodeId\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12&\n" +
	"\fworkspace_id\x18\x04 \x01(\tH\x00R\vworkspaceId\x88\x01\x01B\x0f\n" +
	"\r_workspace_id\"\xb3\x01\n" +
	"\x0eAccessDecision\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\tR\bdecision\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06object\x12\x1c\n" +
	"\toperation\x18\x04 \x01(\tR\toperation\x12;\n" +
	"\vexplanation\x18\x05 \x01(\v2\x19.policy.AccessExplanationR\vexplanation\"\xa5\x03\n" +
	"\x11AccessExplanation\x12\x12\n" +
	"\x04path\x18\x01 \x03(\tR\x04path\x12%\n" +
	"\fpolicy_class\x18\x02 \x01(\tB\x02\x18\x01R\vpolicyClass\x12'\n" +
	"\x0fuser_attributes\x18\x03 \x03(\tR\x0euserAttributes\x12+\n" +
	"\x11object_attributes\x18\x04 \x03(\tR\x10objectAttributes\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12/\n" +
	"\x13constraints_checked\x18\x06 \x03(\tR\x12constraintsChecked\x12E\n" +
	"\x11constraint_denied\x18\a \x01(\v2\x18.policy.ConstraintDenialR\x10constraintDenied\x12H\n" +
	"\x12prohibition_denied\x18\b \x01(\v2\x19.policy.ProhibitionDenialR\x11prohibitionDenied\x12%\n" +
	"\x0epolicy_classes\x18\t \x03(\tR\rpolicyClasses\"@\n" +
	"\x10ConstraintDenial\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xce\x01\n" +
	"\x11CreateNodeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x12I\n" +
	"\n" +
	"properties\x18\x03 \x03(\v2).policy.CreateNodeRequest.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\",\n" +
	"\x11DeleteNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\")\n" +
	"\x0eGetNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"H\n" +
	"\x15FindNodeByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\"4\n" +
	"\x15GetNodesByTypeRequest\x12\x1b\n" +
	"\tnode_type\x18\x01 \x01(\tR\bnodeType\"2\n" +
	"\bNodeList\x12&\n" +
	"\x05nodes\x18\x01 \x03(\v2\x10.policy.NGACNodeR\x05nodes\"Q\n" +
	"\x17CreateAssignmentRequest\x12\x19\n" +
	"\bchild_id\x18\x01 \x01(\tR\achildId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\"Q\n" +
	"\x17RemoveAssignmentRequest\x12\x19\n" +
	"\bchild_id\x18\x01 \x01(\tR\achildId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\"K\n" +
	"\x11IsAssignedRequest\x12\x19\n" +
	"\bchild_id\x18\x01 \x01(\tR\achildId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\"d\n" +
	"\x18CreateAssociationRequest\x12\x13\n" +
	"\x05ua_id\x18\x01 \x01(\tR\x04uaId\x12\x13\n" +
	"\x05oa_id\x18\x02 \x01(\tR\x04oaId\x12\x1e\n" +
	"\n" +
	"operations\x18\x03 \x03(\tR\n" +
	"operations\"D\n" +
	"\x18RemoveAssociationRequest\x12\x13\n" +
	"\x05ua_id\x18\x01 \x01(\tR\x04uaId\x12\x13\n" +
	"\x05oa_id\x18\x02 \x01(\tR\x04oaId\".\n" +
	"\x13GetAncestorsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"0\n" +
	"\x15GetDescendantsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"-\n" +
	"\x12GetChildrenRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\",\n" +
	"\x11GetParentsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"z\n" +
	"\x17BatchCheckAccessRequest\x12 \n" +
	"\fuser_node_id\x18\x01 \x01(\tR\n" +
	"userNodeId\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x02 \x03(\tR\tobjectIds\x12\x1e\n" +
	"\n" +
	"operations\x18\x03 \x03(\tR\n" +
	"operations\"\xac\x01\n" +
	"\x11BatchAccessResult\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.policy.BatchAccessResult.ResultsEntryR\aresults\x1aU\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.policy.ObjectPermissionsR\x05value:\x028\x01\"\xa1\x01\n" +
	"\x11ObjectPermissions\x12L\n" +
	"\vpermissions\x18\x01 \x03(\v2*.policy.ObjectPermissions.PermissionsEntryR\vpermissions\x1a>\n" +
	"\x10PermissionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xb8\x01\n" +
	"\vProhibition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId\x12\x1e\n" +
	"\n" +
	"operations\x18\x04 \x03(\tR\n" +
	"operations\x12\"\n" +
	"\rtarget_oa_ids\x18\x05 \x03(\tR\vtargetOaIds\x12\"\n" +
	"\fintersection\x18\x06 \x01(\bR\fintersection\"\xb5\x01\n" +
	"\x18CreateProhibitionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12\x1e\n" +
	"\n" +
	"operations\x18\x03 \x03(\tR\n" +
	"operations\x12\"\n" +
	"\rtarget_oa_ids\x18\x04 \x03(\tR\vtargetOaIds\x12\"\n" +
	"\fintersection\x18\x05 \x01(\bR\fintersection\".\n" +
	"\x18RemoveProhibitionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"8\n" +
	"\x17ListProhibitionsRequest\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\"J\n" +
	"\x0fProhibitionList\x127\n" +
	"\fprohibitions\x18\x01 \x03(\v2\x13.policy.ProhibitionR\fprohibitions\"]\n" +
	"\x11ProhibitionDenial\x12)\n" +
	"\x10prohibition_name\x18\x01 \x01(\tR\x0fprohibitionName\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\";\n" +
	"\x19RegisterOperationsRequest\x12\x1e\n" +
	"\n" +
	"operations\x18\x01 \x03(\tR\n" +
	"operations\"c\n" +
	"\x1aRegisterOperationsResponse\x12\x1e\n" +
	"\n" +
	"registered\x18\x01 \x03(\tR\n" +
	"registered\x12%\n" +
	"\x0ealready_exists\x18\x02 \x03(\tR\ralreadyExists\"/\n" +
	"\rOperationList\x12\x1e\n" +
	"\n" +
	"operations\x18\x01 \x03(\tR\n" +
	"operations\"K\n" +
	"\x16InvalidateCacheRequest\x12\x19\n" +
	"\bnode_ids\x18\x01 \x03(\tR\anodeIds\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x8a\x01\n" +
	"\x17InvalidateCacheResponse\x12&\n" +
	"\x0fl1_keys_deleted\x18\x01 \x01(\x05R\rl1KeysDeleted\x12&\n" +
	"\x0fl2_rows_deleted\x18\x02 \x01(\x05R\rl2RowsDeleted\x12\x1f\n" +
	"\vnew_version\x18\x03 \x01(\x03R\n" +
	"newVersion2\xaf\b\n" +
	"\rPolicyService\x12A\n" +
	"\vCheckAccess\x12\x1a.policy.CheckAccessRequest\x1a\x16.policy.AccessDecision\x129\n" +
	"\n" +
	"CreateNode\x12\x19.policy.CreateNodeRequest\x1a\x10.policy.NGACNode\x126\n" +
	"\n" +
	"DeleteNode\x12\x19.policy.DeleteNodeRequest\x1a\r.policy.Empty\x123\n" +
	"\aGetNode\x12\x16.policy.GetNodeRequest\x1a\x10.policy.NGACNode\x12A\n" +
	"\x0eFindNodeByName\x12\x1d.policy.FindNodeByNameRequest\x1a\x10.policy.NGACNode\x12A\n" +
	"\x0eGetNodesByType\x12\x1d.policy.GetNodesByTypeRequest\x1a\x10.policy.NodeList\x12G\n" +
	"\x10CreateAssignment\x12\x1f.policy.CreateAssignmentRequest\x1a\x12.policy.Assignment\x12B\n" +
	"\x10RemoveAssignment\x12\x1f.policy.RemoveAssignmentRequest\x1a\r.policy.Empty\x12=\n" +
	"\n" +
	"IsAssigned\x12\x19.policy.IsAssignedRequest\x1a\x14.policy.BoolResponse\x12J\n" +
	"\x11CreateAssociation\x12 .policy.CreateAssociationRequest\x1a\x13.policy.Association\x12D\n" +
	"\x11RemoveAssociation\x12 .policy.RemoveAssociationRequest\x1a\r.policy.Empty\x12=\n" +
	"\fGetAncestors\x12\x1b.policy.GetAncestorsRequest\x1a\x10.policy.NodeList\x12A\n" +
	"\x0eGetDescendants\x12\x1d.policy.GetDescendantsRequest\x1a\x10.policy.NodeList\x12;\n" +
	"\vGetChildren\x12\x1a.policy.GetChildrenRequest\x1a\x10.policy.NodeList\x129\n" +
	"\n" +
	"GetParents\x12\x19.policy.GetParentsRequest\x1a\x10.policy.NodeList\x12*\n" +
	"\n" +
	"InitSchema\x12\r.policy.Empty\x1a\r.policy.Empty\x12)\n" +
	"\tLoadGraph\x12\r.policy.Empty\x1a\r.policy.EmptyB\x1cZ\x1angac-platform/proto/policyb\x06proto3"

var (
	file_proto_policy_policy_proto_rawDescOnce sync.Once
	file_proto_policy_policy_proto_rawDescData []byte
)

func file_proto_policy_policy_proto_rawDescGZIP() []byte {
	file_proto_policy_policy_proto_rawDescOnce.Do(func() {
		file_proto_policy_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_policy_policy_proto_rawDesc), len(file_proto_policy_policy_proto_rawDesc)))
	})
	return file_proto_policy_policy_proto_rawDescData
}

var file_proto_policy_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_proto_policy_policy_proto_goTypes = []any{
	(*Empty)(nil),                      // 0: policy.Empty
	(*BoolResponse)(nil),               // 1: policy.BoolResponse
	(*NGACNode)(nil),                   // 2: policy.NGACNode
	(*Assignment)(nil),                 // 3: policy.Assignment
	(*Association)(nil),                // 4: policy.Association
	(*CheckAccessRequest)(nil),         // 5: policy.CheckAccessRequest
	(*AccessDecision)(nil),             // 6: policy.AccessDecision
	(*AccessExplanation)(nil),          // 7: policy.AccessExplanation
	(*ConstraintDenial)(nil),           // 8: policy.ConstraintDenial
	(*CreateNodeRequest)(nil),          // 9: policy.CreateNodeRequest
	(*DeleteNodeRequest)(nil),          // 10: policy.DeleteNodeRequest
	(*GetNodeRequest)(nil),             // 11: policy.GetNodeRequest
	(*FindNodeByNameRequest)(nil),      // 12: policy.FindNodeByNameRequest
	(*GetNodesByTypeRequest)(nil),      // 13: policy.GetNodesByTypeRequest
	(*NodeList)(nil),                   // 14: policy.NodeList
	(*CreateAssignmentRequest)(nil),    // 15: policy.CreateAssignmentRequest
	(*RemoveAssignmentRequest)(nil),    // 16: policy.RemoveAssignmentRequest
	(*IsAssignedRequest)(nil),          // 17: policy.IsAssignedRequest
	(*CreateAssociationRequest)(nil),   // 18: policy.CreateAssociationRequest
	(*RemoveAssociationRequest)(nil),   // 19: policy.RemoveAssociationRequest
	(*GetAncestorsRequest)(nil),        // 20: policy.GetAncestorsRequest
	(*GetDescendantsRequest)(nil),      // 21: policy.GetDescendantsRequest
	(*GetChildrenRequest)(nil),         // 22: policy.GetChildrenRequest
	(*GetParentsRequest)(nil),          // 23: policy.GetParentsRequest
	(*BatchCheckAccessRequest)(nil),    // 24: policy.BatchCheckAccessRequest
	(*BatchAccessResult)(nil),          // 25: policy.BatchAccessResult
	(*ObjectPermissions)(nil),          // 26: policy.ObjectPermissions
	(*Prohibition)(nil),                // 27: policy.Prohibition
	(*CreateProhibitionRequest)(nil),   // 28: policy.CreateProhibitionRequest
	(*RemoveProhibitionRequest)(nil),   // 29: policy.RemoveProhibitionRequest
	(*ListProhibitionsRequest)(nil),    // 30: policy.ListProhibitionsRequest
	(*ProhibitionList)(nil),            // 31: policy.ProhibitionList
	(*ProhibitionDenial)(nil),          // 32: policy.ProhibitionDenial
	(*RegisterOperationsRequest)(nil),  // 33: policy.RegisterOperationsRequest
	(*RegisterOperationsResponse)(nil), // 34: policy.RegisterOperationsResponse
	(*OperationList)(nil),              // 35: policy.OperationList
	(*InvalidateCacheRequest)(nil),     // 36: policy.InvalidateCacheRequest
	(*InvalidateCacheResponse)(nil),    // 37: policy.InvalidateCacheResponse
	nil,                                // 38: policy.NGACNode.PropertiesEntry
	nil,                                // 39: policy.CreateNodeRequest.PropertiesEntry
	nil,                                // 40: policy.BatchAccessResult.ResultsEntry
	nil,                                // 41: policy.ObjectPermissions.PermissionsEntry
	(*timestamppb.Timestamp)(nil),      // 42: google.protobuf.Timestamp
}
var file_proto_policy_policy_proto_depIdxs = []int32{
	38, // 0: policy.NGACNode.properties:type_name -> policy.NGACNode.PropertiesEntry
	42, // 1: policy.NGACNode.created_at:type_name -> google.protobuf.Timestamp
	7,  // 2: policy.AccessDecision.explanation:type_name -> policy.AccessExplanation
	8,  // 3: policy.AccessExplanation.constraint_denied:type_name -> policy.ConstraintDenial
	32, // 4: policy.AccessExplanation.prohibition_denied:type_name -> policy.ProhibitionDenial
	39, // 5: policy.CreateNodeRequest.properties:type_name -> policy.CreateNodeRequest.PropertiesEntry
	2,  // 6: policy.NodeList.nodes:type_name -> policy.NGACNode
	40, // 7: policy.BatchAccessResult.results:type_name -> policy.BatchAccessResult.ResultsEntry
	41, // 8: policy.ObjectPermissions.permissions:type_name -> policy.ObjectPermissions.PermissionsEntry
	27, // 9: policy.ProhibitionList.prohibitions:type_name -> policy.Prohibition
	26, // 10: policy.BatchAccessResult.ResultsEntry.value:type_name -> policy.ObjectPermissions
	5,  // 11: policy.PolicyService.CheckAccess:input_type -> policy.CheckAccessRequest
	9,  // 12: policy.PolicyService.CreateNode:input_type -> policy.CreateNodeRequest
	10, // 13: policy.PolicyService.DeleteNode:input_type -> policy.DeleteNodeRequest
	11, // 14: policy.PolicyService.GetNode:input_type -> policy.GetNodeRequest
	12, // 15: policy.PolicyService.FindNodeByName:input_type -> policy.FindNodeByNameRequest
	13, // 16: policy.PolicyService.GetNodesByType:input_type -> policy.GetNodesByTypeRequest
	15, // 17: policy.PolicyService.CreateAssignment:input_type -> policy.CreateAssignmentRequest
	16, // 18: policy.PolicyService.RemoveAssignment:input_type -> policy.RemoveAssignmentRequest
	17, // 19: policy.PolicyService.IsAssigned:input_type -> policy.IsAssignedRequest
	18, // 20: policy.PolicyService.CreateAssociation:input_type -> policy.CreateAssociationRequest
	19, // 21: policy.PolicyService.RemoveAssociation:input_type -> policy.RemoveAssociationRequest
	20, // 22: policy.PolicyService.GetAncestors:input_type -> policy.GetAncestorsRequest
	21, // 23: policy.PolicyService.GetDescendants:input_type -> policy.GetDescendantsRequest
	22, // 24: policy.PolicyService.GetChildren:input_type -> policy.GetChildrenRequest
	23, // 25: policy.PolicyService.GetParents:input_type -> policy.GetParentsRequest
	0,  // 26: policy.PolicyService.InitSchema:input_type -> policy.Empty
	0,  // 27: policy.PolicyService.LoadGraph:input_type -> policy.Empty
	6,  // 28: policy.PolicyService.CheckAccess:output_type -> policy.AccessDecision
	2,  // 29: policy.PolicyService.CreateNode:output_type -> policy.NGACNode
	0,  // 30: policy.PolicyService.DeleteNode:output_type -> policy.Empty
	2,  // 31: policy.PolicyService.GetNode:output_type -> policy.NGACNode
	2,  // 32: policy.PolicyService.FindNodeByName:output_type -> policy.NGACNode
	14, // 33: policy.PolicyService.GetNodesByType:output_type -> policy.NodeList
	3,  // 34: policy.PolicyService.CreateAssignment:output_type -> policy.Assignment
	0,  // 35: policy.PolicyService.RemoveAssignment:output_type -> policy.Empty
	1,  // 36: policy.PolicyService.IsAssigned:output_type -> policy.BoolResponse
	4,  // 37: policy.PolicyService.CreateAssociation:output_type -> policy.Association
	0,  // 38: policy.PolicyService.RemoveAssociation:output_type -> policy.Empty
	14, // 39: policy.PolicyService.GetAncestors:output_type -> policy.NodeList
	14, // 40: policy.PolicyService.GetDescendants:output_type -> policy.NodeList
	14, // 41: policy.PolicyService.GetChildren:output_type -> policy.NodeList
	14, // 42: policy.PolicyService.GetParents:output_type -> policy.NodeList
	0,  // 43: policy.PolicyService.InitSchema:output_type -> policy.Empty
	0,  // 44: policy.PolicyService.LoadGraph:output_type -> policy.Empty
	28, // [28:45] is the sub-list for method output_type
	11, // [11:28] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_policy_policy_proto_init() }
func file_proto_policy_policy_proto_init() {
	if File_proto_policy_policy_proto != nil {
		return
	}
	file_proto_policy_policy_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_policy_policy_proto_rawDesc), len(file_proto_policy_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_policy_policy_proto_goTypes,
		DependencyIndexes: file_proto_policy_policy_proto_depIdxs,
		MessageInfos:      file_proto_policy_policy_proto_msgTypes,
	}.Build()
	File_proto_policy_policy_proto = out.File
	file_proto_policy_policy_proto_goTypes = nil
	file_proto_policy_policy_proto_depIdxs = nil
}
