import { request, api, BASE, sql, rec, saveResults } from './lib.mjs'
import { buildWorld, ctx } from './world.mjs'
const W = await buildWorld()
const F = 'flow12-cross-tenant-api'
const j = (x) => JSON.stringify(x).slice(0, 200)
const ch = sql(`select id from channels where workspace_id = '${W.wsA}' and name = 'general' limit 1`)
const secret = 'Bí mật API ' + W.run
const post = await api(ctx, W.O, 'POST', `/channels/${ch}/messages`, { content: secret })
rec(F, 'owner posts a tenant-A message (setup)', post.status === 201, `${post.status}`)
const s1 = await api(ctx, W.X, 'GET', `/channels/${ch}/search?q=${encodeURIComponent('Bí mật')}`)
rec(F, 'outsider channel search on tenant-A channel refused (403)', s1.status === 403, `${s1.status} ${j(s1.body)}`)
const s2 = await api(ctx, W.X, 'GET', `/channels/${ch}/messages`)
rec(F, 'outsider reads tenant-A channel messages refused (403)', s2.status === 403 && !JSON.stringify(s2.body).includes(secret), `${s2.status} ${j(s2.body)}`)
const s3 = await api(ctx, W.X, 'GET', `/workspaces/${W.wsA}/contacts`)
rec(F, 'outsider contacts of tenant A refused (403)', s3.status === 403, `${s3.status} ${j(s3.body)}`)
const s4 = await api(ctx, W.X, 'GET', `/workspaces/${W.wsA}/members`)
rec(F, 'outsider member list of tenant A refused (403)', s4.status === 403, `${s4.status} ${j(s4.body)}`)
const s5 = await api(ctx, W.X, 'GET', '/channels/unread')
rec(F, 'outsider unread list has no tenant-A channel', s5.status === 200 && !JSON.stringify(s5.body).includes(ch), `${s5.status} ${j(s5.body)}`)
const s6 = await api(ctx, W.X, 'GET', '/notifications')
rec(F, 'outsider notifications contain no tenant-A text', s6.status === 200 && !JSON.stringify(s6.body).includes(secret), `${s6.status}`)
const s7 = await api(ctx, W.X, 'POST', `/channels/${ch}/messages`, { content: 'xâm nhập' })
rec(F, 'outsider cannot post into tenant-A channel (403)', s7.status === 403, `${s7.status} ${j(s7.body)}`)
const s8 = await api(ctx, W.X, 'GET', `/workspaces/${W.wsA}/asset-types`)
rec(F, 'outsider asset types of tenant A refused (403)', s8.status === 403, `${s8.status} ${j(s8.body)}`)
const s9 = await api(ctx, W.X, 'GET', `/approval/templates`)
rec(F, 'outsider approval templates list holds no tenant-A template', s9.status !== 200 || !JSON.stringify(s9.body).includes('Chi'), `${s9.status} ${j(s9.body)}`)
saveResults('xtenant-api')
console.log('DONE xtenant')
