// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/approval/approval.proto

package approval

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApprovalService_CreateTemplate_FullMethodName        = "/approval.ApprovalService/CreateTemplate"
	ApprovalService_GetTemplate_FullMethodName           = "/approval.ApprovalService/GetTemplate"
	ApprovalService_ListTemplates_FullMethodName         = "/approval.ApprovalService/ListTemplates"
	ApprovalService_UpdateTemplate_FullMethodName        = "/approval.ApprovalService/UpdateTemplate"
	ApprovalService_CreateRequest_FullMethodName         = "/approval.ApprovalService/CreateRequest"
	ApprovalService_Approve_FullMethodName               = "/approval.ApprovalService/Approve"
	ApprovalService_Reject_FullMethodName                = "/approval.ApprovalService/Reject"
	ApprovalService_BatchApprove_FullMethodName          = "/approval.ApprovalService/BatchApprove"
	ApprovalService_GetPending_FullMethodName            = "/approval.ApprovalService/GetPending"
	ApprovalService_GetHistory_FullMethodName            = "/approval.ApprovalService/GetHistory"
	ApprovalService_GetMyRequests_FullMethodName         = "/approval.ApprovalService/GetMyRequests"
	ApprovalService_GetDepartmentRequests_FullMethodName = "/approval.ApprovalService/GetDepartmentRequests"
	ApprovalService_GetAuditLog_FullMethodName           = "/approval.ApprovalService/GetAuditLog"
)

// ApprovalServiceClient is the client API for ApprovalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ApprovalService manages template-driven multi-step approval workflows.
// Uses NGAC structural graph for approver resolution, and denormalized tables
// for high-performance query without per-item graph traversal.
type ApprovalServiceClient interface {
	// Template management (admin)
	CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*ApprovalTemplate, error)
	GetTemplate(ctx context.Context, in *GetTemplateRequest, opts ...grpc.CallOption) (*ApprovalTemplate, error)
	ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*TemplateList, error)
	UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*ApprovalTemplate, error)
	// Approval request lifecycle
	CreateRequest(ctx context.Context, in *CreateApprovalRequestReq, opts ...grpc.CallOption) (*ApprovalRequest, error)
	Approve(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*ApprovalRequest, error)
	Reject(ctx context.Context, in *RejectRequest, opts ...grpc.CallOption) (*ApprovalRequest, error)
	BatchApprove(ctx context.Context, in *BatchApproveRequest, opts ...grpc.CallOption) (*BatchApproveResponse, error)
	// Query tabs
	GetPending(ctx context.Context, in *GetPendingRequest, opts ...grpc.CallOption) (*ApprovalList, error)
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*ApprovalList, error)
	GetMyRequests(ctx context.Context, in *GetMyRequestsRequest, opts ...grpc.CallOption) (*ApprovalList, error)
	GetDepartmentRequests(ctx context.Context, in *GetDepartmentRequestsRequest, opts ...grpc.CallOption) (*ApprovalList, error)
	// Audit
	GetAuditLog(ctx context.Context, in *GetAuditLogRequest, opts ...grpc.CallOption) (*AuditLogList, error)
}

type approvalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApprovalServiceClient(cc grpc.ClientConnInterface) ApprovalServiceClient {
	return &approvalServiceClient{cc}
}

func (c *approvalServiceClient) CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*ApprovalTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalTemplate)
	err := c.cc.Invoke(ctx, ApprovalService_CreateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) GetTemplate(ctx context.Context, in *GetTemplateRequest, opts ...grpc.CallOption) (*ApprovalTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalTemplate)
	err := c.cc.Invoke(ctx, ApprovalService_GetTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*TemplateList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateList)
	err := c.cc.Invoke(ctx, ApprovalService_ListTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*ApprovalTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalTemplate)
	err := c.cc.Invoke(ctx, ApprovalService_UpdateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) CreateRequest(ctx context.Context, in *CreateApprovalRequestReq, opts ...grpc.CallOption) (*ApprovalRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalRequest)
	err := c.cc.Invoke(ctx, ApprovalService_CreateRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) Approve(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*ApprovalRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalRequest)
	err := c.cc.Invoke(ctx, ApprovalService_Approve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) Reject(ctx context.Context, in *RejectRequest, opts ...grpc.CallOption) (*ApprovalRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalRequest)
	err := c.cc.Invoke(ctx, ApprovalService_Reject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) BatchApprove(ctx context.Context, in *BatchApproveRequest, opts ...grpc.CallOption) (*BatchApproveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchApproveResponse)
	err := c.cc.Invoke(ctx, ApprovalService_BatchApprove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) GetPending(ctx context.Context, in *GetPendingRequest, opts ...grpc.CallOption) (*ApprovalList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalList)
	err := c.cc.Invoke(ctx, ApprovalService_GetPending_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*ApprovalList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalList)
	err := c.cc.Invoke(ctx, ApprovalService_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) GetMyRequests(ctx context.Context, in *GetMyRequestsRequest, opts ...grpc.CallOption) (*ApprovalList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalList)
	err := c.cc.Invoke(ctx, ApprovalService_GetMyRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) GetDepartmentRequests(ctx context.Context, in *GetDepartmentRequestsRequest, opts ...grpc.CallOption) (*ApprovalList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalList)
	err := c.cc.Invoke(ctx, ApprovalService_GetDepartmentRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalServiceClient) GetAuditLog(ctx context.Context, in *GetAuditLogRequest, opts ...grpc.CallOption) (*AuditLogList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditLogList)
	err := c.cc.Invoke(ctx, ApprovalService_GetAuditLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApprovalServiceServer is the server API for ApprovalService service.
// All implementations must embed UnimplementedApprovalServiceServer
// for forward compatibility.
//
// ApprovalService manages template-driven multi-step approval workflows.
// Uses NGAC structural graph for approver resolution, and denormalized tables
// for high-performance query without per-item graph traversal.
type ApprovalServiceServer interface {
	// Template management (admin)
	CreateTemplate(context.Context, *CreateTemplateRequest) (*ApprovalTemplate, error)
	GetTemplate(context.Context, *GetTemplateRequest) (*ApprovalTemplate, error)
	ListTemplates(context.Context, *ListTemplatesRequest) (*TemplateList, error)
	UpdateTemplate(context.Context, *UpdateTemplateRequest) (*ApprovalTemplate, error)
	// Approval request lifecycle
	CreateRequest(context.Context, *CreateApprovalRequestReq) (*ApprovalRequest, error)
	Approve(context.Context, *ApproveRequest) (*ApprovalRequest, error)
	Reject(context.Context, *RejectRequest) (*ApprovalRequest, error)
	BatchApprove(context.Context, *BatchApproveRequest) (*BatchApproveResponse, error)
	// Query tabs
	GetPending(context.Context, *GetPendingRequest) (*ApprovalList, error)
	GetHistory(context.Context, *GetHistoryRequest) (*ApprovalList, error)
	GetMyRequests(context.Context, *GetMyRequestsRequest) (*ApprovalList, error)
	GetDepartmentRequests(context.Context, *GetDepartmentRequestsRequest) (*ApprovalList, error)
	// Audit
	GetAuditLog(context.Context, *GetAuditLogRequest) (*AuditLogList, error)
	mustEmbedUnimplementedApprovalServiceServer()
}

// UnimplementedApprovalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApprovalServiceServer struct{}

func (UnimplementedApprovalServiceServer) CreateTemplate(context.Context, *CreateTemplateRequest) (*ApprovalTemplate, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedApprovalServiceServer) GetTemplate(context.Context, *GetTemplateRequest) (*ApprovalTemplate, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTemplate not implemented")
}
func (UnimplementedApprovalServiceServer) ListTemplates(context.Context, *ListTemplatesRequest) (*TemplateList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTemplates not implemented")
}
func (UnimplementedApprovalServiceServer) UpdateTemplate(context.Context, *UpdateTemplateRequest) (*ApprovalTemplate, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTemplate not implemented")
}
func (UnimplementedApprovalServiceServer) CreateRequest(context.Context, *CreateApprovalRequestReq) (*ApprovalRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRequest not implemented")
}
func (UnimplementedApprovalServiceServer) Approve(context.Context, *ApproveRequest) (*ApprovalRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method Approve not implemented")
}
func (UnimplementedApprovalServiceServer) Reject(context.Context, *RejectRequest) (*ApprovalRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method Reject not implemented")
}
func (UnimplementedApprovalServiceServer) BatchApprove(context.Context, *BatchApproveRequest) (*BatchApproveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchApprove not implemented")
}
func (UnimplementedApprovalServiceServer) GetPending(context.Context, *GetPendingRequest) (*ApprovalList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPending not implemented")
}
func (UnimplementedApprovalServiceServer) GetHistory(context.Context, *GetHistoryRequest) (*ApprovalList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedApprovalServiceServer) GetMyRequests(context.Context, *GetMyRequestsRequest) (*ApprovalList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyRequests not implemented")
}
func (UnimplementedApprovalServiceServer) GetDepartmentRequests(context.Context, *GetDepartmentRequestsRequest) (*ApprovalList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDepartmentRequests not implemented")
}
func (UnimplementedApprovalServiceServer) GetAuditLog(context.Context, *GetAuditLogRequest) (*AuditLogList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuditLog not implemented")
}
func (UnimplementedApprovalServiceServer) mustEmbedUnimplementedApprovalServiceServer() {}
func (UnimplementedApprovalServiceServer) testEmbeddedByValue()                         {}

// UnsafeApprovalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApprovalServiceServer will
// result in compilation errors.
type UnsafeApprovalServiceServer interface {
	mustEmbedUnimplementedApprovalServiceServer()
}

func RegisterApprovalServiceServer(s grpc.ServiceRegistrar, srv ApprovalServiceServer) {
	// If the following call panics, it indicates UnimplementedApprovalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApprovalService_ServiceDesc, srv)
}

func _ApprovalService_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_CreateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).CreateTemplate(ctx, req.(*CreateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_GetTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).GetTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_GetTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).GetTemplate(ctx, req.(*GetTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_ListTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).ListTemplates(ctx, req.(*ListTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_UpdateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).UpdateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_UpdateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).UpdateTemplate(ctx, req.(*UpdateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_CreateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApprovalRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).CreateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_CreateRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).CreateRequest(ctx, req.(*CreateApprovalRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_Approve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).Approve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_Approve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).Approve(ctx, req.(*ApproveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_Reject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).Reject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_Reject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).Reject(ctx, req.(*RejectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_BatchApprove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchApproveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).BatchApprove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_BatchApprove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).BatchApprove(ctx, req.(*BatchApproveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_GetPending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).GetPending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_GetPending_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).GetPending(ctx, req.(*GetPendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_GetMyRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).GetMyRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_GetMyRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).GetMyRequests(ctx, req.(*GetMyRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_GetDepartmentRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepartmentRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).GetDepartmentRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_GetDepartmentRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).GetDepartmentRequests(ctx, req.(*GetDepartmentRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalService_GetAuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalServiceServer).GetAuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalService_GetAuditLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalServiceServer).GetAuditLog(ctx, req.(*GetAuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApprovalService_ServiceDesc is the grpc.ServiceDesc for ApprovalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApprovalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "approval.ApprovalService",
	HandlerType: (*ApprovalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTemplate",
			Handler:    _ApprovalService_CreateTemplate_Handler,
		},
		{
			MethodName: "GetTemplate",
			Handler:    _ApprovalService_GetTemplate_Handler,
		},
		{
			MethodName: "ListTemplates",
			Handler:    _ApprovalService_ListTemplates_Handler,
		},
		{
			MethodName: "UpdateTemplate",
			Handler:    _ApprovalService_UpdateTemplate_Handler,
		},
		{
			MethodName: "CreateRequest",
			Handler:    _ApprovalService_CreateRequest_Handler,
		},
		{
			MethodName: "Approve",
			Handler:    _ApprovalService_Approve_Handler,
		},
		{
			MethodName: "Reject",
			Handler:    _ApprovalService_Reject_Handler,
		},
		{
			MethodName: "BatchApprove",
			Handler:    _ApprovalService_BatchApprove_Handler,
		},
		{
			MethodName: "GetPending",
			Handler:    _ApprovalService_GetPending_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _ApprovalService_GetHistory_Handler,
		},
		{
			MethodName: "GetMyRequests",
			Handler:    _ApprovalService_GetMyRequests_Handler,
		},
		{
			MethodName: "GetDepartmentRequests",
			Handler:    _ApprovalService_GetDepartmentRequests_Handler,
		},
		{
			MethodName: "GetAuditLog",
			Handler:    _ApprovalService_GetAuditLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/approval/approval.proto",
}
